### ISSUE TITLE
Add Apache configuration language support

### ISSUE THREAD

**Issue by HenryGR** [EnlighterJS/EnlighterJS#101]
Please add Apache configuration language, it did not display correctly with any of the current languages.

**Comment by AndiDittrich** [comment]
hi @HenryGR ,

the "generic" mode looks not great but it's working. the wordpress forums breaks your code - maybe you can post a screenshot ?

**generic example**

![image](https://user-images.githubusercontent.com/1474107/79774054-920ab480-8332-11ea-9c4c-485dc1af2575.png)

**Comment by AndiDittrich** [comment]
support has been added to the master branch
![image](https://user-images.githubusercontent.com/1474107/79780402-29c0d080-833c-11ea-90c1-e6fb7c10a51c.png)
