### ISSUE TITLE
WCAG accessibility issues

### ISSUE THREAD

**Issue by rajrsingh** [EnlighterJS/EnlighterJS#105]
Web design folks are telling me Enlighter isn't passing the web accessibility guidelines for color contrast to which we need to conform. Is there an Enlighter theme out there that pays attention to this issue?

sample page: https://dev-start.intersystems.com/language-quickstarts/sql-quickstart/
tested with: https://webaim.org/resources/contrastchecker/

p.s. Great library and thanks for all the work!

**Comment by AndiDittrich** [comment]
short answer: no

just create a custom theme which matches your requirements.

btw. your current theme seems to be broken...

**Comment by rajrsingh** [comment]
OK I think I'll try to use this pygments stylesheet that has the same goal https://github.com/mpchadwick/pygments-high-contrast-stylesheets

**Comment by rajrsingh** [comment]
In case someone finds this thread via a Google search, I was able to make a theme that passes the WCAG AA standard. Ping me if you need it.
