### ISSUE TITLE
Wrong highlighting for CSS language

### ISSUE THREAD

**Issue by AinaBeryl** [EnlighterJS/EnlighterJS#107]
Hi there,
I'm reworking a website, in the older version I have the version 3.10.0 of the plugin, and in the new version of the website I have the 4.2 CE.

In the older version, all's right : selectors, properties, values...
In the newer version, it looks broken, especially with ":".
Here is a screenshot with Atomic theme:
![enlighter-issue](https://user-images.githubusercontent.com/48152765/82416133-db593b80-9a79-11ea-986b-2cd6106bfb4c.jpg)

For the older version, here is the markup generated:
`<ol class="hoverEnabled atomicEnlighterJS EnlighterJS"><li class=" odd"><span class="kw1">img</span><span class="br0">{</span><span class=""></span></li><li class=" even"><span class="">    </span><span class="kw3">filter</span><span class="sy0">:</span><span class="">contrast</span><span class="br0">(</span><span class="nu0">150%</span><span class="br0">)</span><span class=""> grayscale</span><span class="br0">(</span><span class="nu0">100%</span><span class="br0">)</span><span class="sy0">;</span><span class=""></span></li><li class=" odd"><span class=""></span><span class="br0">}</span></li></ol>`

And for the actual version, see how &lt;span&gt; placement and classes are different:
`<div class="enlighter" style=""><div class=""><div><span class="enlighter-text">img</span><span class="enlighter-g1">{</span><span class="enlighter-text"></span></div></div><div class=""><div><span class="enlighter-text">    </span><span class="enlighter-x12">filter</span><span class="enlighter-x15">:contrast</span><span class="enlighter-g1">(</span><span class="enlighter-x13">150%</span><span class="enlighter-g1">)</span><span class="enlighter-text"> grayscale</span><span class="enlighter-g1">(</span><span class="enlighter-x13">100%</span><span class="enlighter-g1">)</span><span class="enlighter-text">;</span></div></div><div class=""><div><span class="enlighter-text"></span><span class="enlighter-g1">}</span></div></div></div>`

Thanks!

**Comment by AinaBeryl** [comment]
Ok, thank you for the answer and the list of tokens!

I'm not sure the issue come from the themes (excluding colors and styles, but this is not a problem to change that ^^), because where we had in 3.10.0 this: `<span class="sy0">:</span><span class="">contrast</span>` (a span for ":", and a span for the property), we now have `<span class="enlighter-x15">:contrast</span>`, an unique span including both.

According to the doc you shared, x15 is for CSS Pseudo Elements/Selectors. The new script seems to detect ":XXX" as a pseudo-element, even if it is between brackets. Doesn't it should be here `<span class="enlighter-g0">:</span><span class="enlighter-x12">contrast</span>`?

**Comment by AndiDittrich** [comment]
use a space between colon and contrast...

the general "issue" with syntax highlighting is performance...regular editors/IDE are creating an AST which provides a full-featured syntax highlighting. this is a perfect solution for workstations but cause a major performance impact on web-pages - therefore EnlighterJS uses a much simpler regex approach. 

the [css language support](https://github.com/EnlighterJS/EnlighterJS/blob/master/src/lang/css.js) doesn't take care of the token position (inside/outside rule block)

i've no "bulletproof" solution for css files atm - a secondary tokenizer stage could solve this but this may cause other issues (css snippets without selectors..)

**Comment by AinaBeryl** [comment]
Ok, I understand the performance impact it could be to complexify the regex. I'll add spaces on all my code chunks! :)
Thanks again for your answers, and have a nice day!

**Comment by AndiDittrich** [comment]
as a possible solution, i can extract the selectors as separate token and remove the pseudo/id/class rules from the ruleset:

![image](https://user-images.githubusercontent.com/1474107/82426482-31cd7680-9a88-11ea-8f73-f044e5e03ae6.png)

**Comment by AinaBeryl** [comment]
If it means that x10 (id), x11 (class) and x15 (pseudo) disappear, then it will cause an issue for other people who want to keep the highlighting on selectors (and I'm part of them :) ). Maybe the best solution is simply to add spaces as you said :)

**Comment by AndiDittrich** [comment]
the will be processed by the second stage tokenizer.

**Comment by AndiDittrich** [comment]
example:
![image](https://user-images.githubusercontent.com/1474107/82427943-0fd4f380-9a8a-11ea-96e4-6b5e2c92c403.png)

**Comment by AinaBeryl** [comment]
It looks perfect!

**Comment by AndiDittrich** [comment]
it's working for css but causes major issues for less/scss...

**Comment by AinaBeryl** [comment]
Hi @AndiDittrich,
just found another issue with CSS language, with units regex (x13):
![image](https://user-images.githubusercontent.com/48152765/82747067-0bfce600-9d96-11ea-807b-53a26f1210bf.png)
The 100vmax is cut before "x", it should be after.
Bye!

**Comment by AinaBeryl** [comment]
And sometimes, pseudo-classes and pseudo-elements are not parsed as such :)
![image](https://user-images.githubusercontent.com/48152765/82748155-086e5c80-9da0-11ea-979d-6b57e410da13.png)
See lines 1 and 7 where only the first one is parsed.

**Comment by AndiDittrich** [comment]
thanks i'll check this - could you provide the examples above as code please ?

**Comment by AinaBeryl** [comment]
Of course!
`body::before {
    content: "";
    display: block;
    position: fixed;
    box-shadow: 0 0 0 100vmax rgba(255,128,0,0.2);
    mix-blend-mode: multiply;
    z-index: 9;
}`
became
`<div class="enlighter" style=""><div class=""><div><span class="enlighter-x12">body</span><span class="enlighter-x15">::before</span><span class="enlighter-text"> </span><span class="enlighter-g1">{</span><span class="enlighter-text"></span></div></div><div class=""><div><span class="enlighter-text">    </span><span class="enlighter-x12">content</span><span class="enlighter-text">: </span><span class="enlighter-s0">""</span><span class="enlighter-text">;</span></div></div><div class=""><div><span class="enlighter-text">    </span><span class="enlighter-x12">display</span><span class="enlighter-text">: block;</span></div></div><div class=""><div><span class="enlighter-text">    </span><span class="enlighter-x12">position</span><span class="enlighter-text">: fixed;</span></div></div><div class="enlighter-special"><div><span class="enlighter-text">    </span><span class="enlighter-x12">box-shadow</span><span class="enlighter-text">: </span><span class="enlighter-x13">0 </span><span class="enlighter-x13">0 </span><span class="enlighter-x13">0 </span><span class="enlighter-x13">100vma</span><span class="enlighter-text">x rgba</span><span class="enlighter-g1">(</span><span class="enlighter-x13">255</span><span class="enlighter-text">,</span><span class="enlighter-x13">128</span><span class="enlighter-text">,</span><span class="enlighter-x13">0</span><span class="enlighter-text">,</span><span class="enlighter-x13">0.</span><span class="enlighter-x13">2</span><span class="enlighter-g1">)</span><span class="enlighter-text">;</span></div></div><div class=""><div><span class="enlighter-text">    </span><span class="enlighter-x12">mix-blend-mode</span><span class="enlighter-text">: multiply;</span></div></div><div class=""><div><span class="enlighter-text">    </span><span class="enlighter-x12">z-index</span><span class="enlighter-text">: </span><span class="enlighter-x13">9</span><span class="enlighter-text">;</span></div></div><div class=""><div><span class="enlighter-text"></span><span class="enlighter-g1">}</span></div></div></div>`

and

`p a[href]:not([href^="javascript:"]):not([href^="#"])::after{
    content: " (" attr(href) ")";
}
p a[data-lienprint]::after{
    content: " (" attr(data-lienprint) ")";
}
p a[href]:not([href^="javascript:"]):not([href^="#"])::after,
p a[data-lienprint]::after{
    opacity: 0.8;
    font-size: 0.8em;
}`
became
`<div class="enlighter" style=""><div class=""><div><span class="enlighter-text">p a</span><span class="enlighter-g1">[</span><span class="enlighter-text">href</span><span class="enlighter-g1">]</span><span class="enlighter-x15">:not</span><span class="enlighter-g1">([</span><span class="enlighter-text">href^=</span><span class="enlighter-s0">"javascript:"</span><span class="enlighter-g1">])</span><span class="enlighter-text">:not</span><span class="enlighter-g1">([</span><span class="enlighter-text">href^=</span><span class="enlighter-s0">"#"</span><span class="enlighter-g1">])</span><span class="enlighter-text">::after</span><span class="enlighter-g1">{</span><span class="enlighter-text"></span></div></div><div class=""><div><span class="enlighter-text">    </span><span class="enlighter-x12">content</span><span class="enlighter-text">: </span><span class="enlighter-s0">" ("</span><span class="enlighter-text"> attr</span><span class="enlighter-g1">(</span><span class="enlighter-text">href</span><span class="enlighter-g1">)</span><span class="enlighter-text"> </span><span class="enlighter-s0">")"</span><span class="enlighter-text">;</span></div></div><div class=""><div><span class="enlighter-text"></span><span class="enlighter-g1">}</span><span class="enlighter-text"></span></div></div><div class=""><div><span class="enlighter-text">p a</span><span class="enlighter-g1">[</span><span class="enlighter-text">data-lienprint</span><span class="enlighter-g1">]</span><span class="enlighter-x15">::after</span><span class="enlighter-g1">{</span><span class="enlighter-text"></span></div></div><div class=""><div><span class="enlighter-text">    </span><span class="enlighter-x12">content</span><span class="enlighter-text">: </span><span class="enlighter-s0">" ("</span><span class="enlighter-text"> attr</span><span class="enlighter-g1">(</span><span class="enlighter-text">data-lienprint</span><span class="enlighter-g1">)</span><span class="enlighter-text"> </span><span class="enlighter-s0">")"</span><span class="enlighter-text">;</span></div></div><div class=""><div><span class="enlighter-text"></span><span class="enlighter-g1">}</span><span class="enlighter-text"></span></div></div><div class=""><div><span class="enlighter-text">p a</span><span class="enlighter-g1">[</span><span class="enlighter-text">href</span><span class="enlighter-g1">]</span><span class="enlighter-x15">:not</span><span class="enlighter-g1">([</span><span class="enlighter-text">href^=</span><span class="enlighter-s0">"javascript:"</span><span class="enlighter-g1">])</span><span class="enlighter-text">:not</span><span class="enlighter-g1">([</span><span class="enlighter-text">href^=</span><span class="enlighter-s0">"#"</span><span class="enlighter-g1">])</span><span class="enlighter-text">::after,</span></div></div><div class=""><div><span class="enlighter-text">p a</span><span class="enlighter-g1">[</span><span class="enlighter-text">data-lienprint</span><span class="enlighter-g1">]</span><span class="enlighter-x15">::after</span><span class="enlighter-g1">{</span><span class="enlighter-text"></span></div></div><div class=""><div><span class="enlighter-text">    </span><span class="enlighter-x12">opacity</span><span class="enlighter-text">: </span><span class="enlighter-x13">0.</span><span class="enlighter-x13">8</span><span class="enlighter-text">;</span></div></div><div class=""><div><span class="enlighter-text">    </span><span class="enlighter-x12">font-size</span><span class="enlighter-text">: </span><span class="enlighter-x13">0.</span><span class="enlighter-x13">8em</span><span class="enlighter-text">;</span></div></div><div class=""><div><span class="enlighter-text"></span><span class="enlighter-g1">}</span></div></div></div>`

(sorry for the awful formatting, it looks like the "insert code" button strips new lines)

**Comment by AndiDittrich** [comment]
no sry, the css from above to copy+paste it into the dev environment

**Comment by AinaBeryl** [comment]
You have both raw code and parsed code in my previous message, is that what you need? (maybe you didn't noticed raw code because it's stuck to the parsed one)

**Comment by AndiDittrich** [comment]
sry i didn't noticed that due to the inline code - btw you can use 3 backticks + language identifier on GitHub for block highlighting

**Comment by AinaBeryl** [comment]
Oh, thanks for the tip, I edited the message! :)

**Comment by AndiDittrich** [comment]
EnlighterJS v3.4.0 includes some enhancements in the css ruleset which solves your issue above:
![image](https://user-images.githubusercontent.com/1474107/85928380-d3788c80-b8ac-11ea-8d5b-78e3c78687f1.png)
