### ISSUE TITLE
Transferring settings / styles

### ISSUE THREAD

**Issue by ajtruckle** [EnlighterJS/EnlighterJS#113]
I am playing with my staging area and a new theme for my website.

How do I transfer my current enlighterjs style overrides etc. from one to other? At the moment staging area is reset to defaults.

Thanks.

**Comment by AndiDittrich** [comment]
i assume that you're referring to the WordPress plugin ?

* in case you've used the theme customizer: copy the database
* manual changes: copy all changed files manually

**Comment by ajtruckle** [comment]
I have got myself in a pickle.

See:

https://www.publictalksoftware.co.uk/2020/05/meeting-schedule-assistant-version-20-1-6-newsletter/

So this is an example of a “post”. Although bbPress is the same.

I remember now that I have a “enlighter\trucklesoft.css” file that was in my last child theme folder.

But now I am not sure where it should go.

**Comment by AndiDittrich** [comment]
into the same location (of your theme or child theme)

**Comment by ajtruckle** [comment]
This is the themes folder structure.

**Comment by AndiDittrich** [comment]
then create a folder named `enlighter` into this directory as mentioned in the docs and put your css theme into this directory

**Comment by ajtruckle** [comment]
Sorted. I had to put it in the parent themes folder - not the child themes.

**Comment by AndiDittrich** [comment]
in case you have a child theme, use the child theme (as written in the docs..)

**Comment by ajtruckle** [comment]
I saw that clearly in the docs. But when I put the folder in the child theme it did not show up.

When I put it in the parent theme it did show up.

Note that both the parent and the child theme are supplied by the vendor.

**Comment by AndiDittrich** [comment]
which theme is enabled in WordPress ? the child or the parent ?

**Comment by ajtruckle** [comment]
Sorted. Thanks.
