### ISSUE TITLE
XML/HTML: dot chars within attribute names not recognized

### ISSUE THREAD

**Issue by deunlee** [EnlighterJS/EnlighterJS#115]
Hi there,
I use the Vue directive in HTML tags, but in some cases there are problems with rendering not working properly. I am using the WordPress plugin 4.2 CE and the EnlighterJS version is 3.3.0.

```
<div v-if="type === 'A'">Type A</div>

<img v-bind="item" v-bind:id="'thumb-' + item.id">

<div v-bind:text-content.prop="message">Content</div>
```

Rendered in VSCode:
![vsc](https://user-images.githubusercontent.com/54697735/85913623-5976e200-b871-11ea-99bd-36e810fd0ca0.PNG)

Rendered in EnlighterJS :
![en](https://user-images.githubusercontent.com/54697735/85913624-5b40a580-b871-11ea-91e7-2251d7761684.PNG)

Thanks.

**Comment by AndiDittrich** [comment]
hi @deunlee 

thanks for your report. it has been fixed in the master branch

**Comment by deunlee** [comment]
Thanks!
