### ISSUE TITLE
Line highlighting not working in Classic and MooToo themes

### ISSUE THREAD

**Issue by woolseyj** [EnlighterJS/EnlighterJS#117]
I have been using the Enlighter - Customizable Syntax Highlighter Wordpress plugin with the Classic theme on my site for a while.  Recently I noticed that line highlighting is no longer working.  I checked across the various themes and they all seem to highlight appropriately except for the Classic and MooToo themes.  I really prefer the Classic theme over the others and would like to get this working again.  Any help would be greatly appreciated.

**Comment by AndiDittrich** [comment]
i cannot identify any issues regarding the `mowtwo` theme (the default grey might be a bit too light)

![image](https://user-images.githubusercontent.com/1474107/86937298-5e744500-c13f-11ea-8278-8813eca3e6b7.png)

**Comment by AndiDittrich** [comment]
issue has been fixed in the master branch

![image](https://user-images.githubusercontent.com/1474107/86937495-9aa7a580-c13f-11ea-8151-f2bef47e7243.png)

**Comment by woolseyj** [comment]
That is awesome!  When will the new plugin update be released?  If it will be a while, what CSS code do I add?
By the way, my version is 4.2.

**Comment by AndiDittrich** [comment]
in a few weeks. you can just override the `enlighterjs.min.css` file
