### ISSUE TITLE
Add support for # comments in PHP

### ISSUE THREAD

**Issue by viktorix** [EnlighterJS/EnlighterJS#118]
Noticed today comments using # in PHP aren't treated as comments, which can causes issues with the rest of the highlighting in specific situations. Specifically, I noticed an apostrophe in a # comment (for example, the word "don't") will screw up highlighting the rows that follow. 

![image](https://user-images.githubusercontent.com/1692600/87228437-4551db00-c36f-11ea-8de0-5f92c37abbd4.png)

For reference, [PHP comments](https://www.php.net/manual/en/language.basic-syntax.comments.php) documentation.

**Comment by AndiDittrich** [comment]
thanks, fixed in the master branch
