### ISSUE TITLE
UTF-8 support in PHP labels

### ISSUE THREAD

**Issue by drmad** [EnlighterJS/EnlighterJS#120]
Hi.

[The PHP manual](https://www.php.net/manual/en/language.variables.basics.php) says that any multi-byte UTF-8 character is valid for variable names and any other label, like function names.

So this is valid PHP code: 

```
function AñadirAcción($acción) 
{ 
   $░▒▓█Coração_do_Æsir😝█▓▒░ = $acción;
}
```

That weird variable is unlikely 😃 but it's a valid one, and spanish, portuguese, and other non-english speakers can use native language labels in PHP.

EnlighterJS [uses a simple regex](https://github.com/EnlighterJS/EnlighterJS/blob/master/src/lang/php.js#L82) `\$[A-Z_][\w]*` for (at least) variables which doesn't include those characters, coloring wrong that code:

![imagen](https://user-images.githubusercontent.com/1307948/87812067-40849f80-c825-11ea-8a90-7cfa1a15b765.png)

The PHP manual suggests a regex for a valid PHP label: `[a-zA-Z_\x80-\xff][a-zA-Z0-9_\x80-\xff]`.

Thanks!

**Comment by AndiDittrich** [comment]
Hi @drmad ,

it's not a big issue to change this - most of the EnlighterJS languages doesn't support unicode.

**Comment by AndiDittrich** [comment]
but i cannot find any reference in the manual regarding "multibyte" names - it only seems that a small subset of the codepoints `128...255` is supported ?!

**Comment by drmad** [comment]
Is not a codepoint range, is a byte value range. Put two to four of those (specially crafted) 128-255 value bytes together, and almost every program will show an Unicode character instead.

A single 128-255 byte is not UTF-8, but it was used with pre-unicode code pages, like ISO-8859-1, so in theory you could used them in PHP also.

**Comment by AndiDittrich** [comment]
the question is: is there an official reference which states that php supports utf8 multibyte characters.. ?

**Comment by drmad** [comment]
Bear in mind that the PHP parser doesn't care about UTF-8, it just see bytes. But we're talking here about _the human representation_ of those bytes. [The manual](https://www.php.net/manual/en/language.variables.basics.php) says:

> A valid variable name starts with a letter or underscore, followed by any number of letters, numbers, or underscores

and

> Note: For our purposes here, a letter is a-z, A-Z, and the bytes from 128 through 255 (0x80-0xff). 

So, using Windows ASCII for representing, the byte sequence `a├▒o` (97, 195, 177, 111) is a valid variable name. In UTF-8, those bytes will show `año` ("year" in spanish).

**Comment by AndiDittrich** [comment]
keep in mind that regular expression works on characters, not on bytes - this requires a much more generic expression:

![image](https://user-images.githubusercontent.com/1474107/87869802-d134ba00-c9a2-11ea-8d54-ae3d8388049d.png)

but generally this php behaviour is only a side effect of the parser and can be threatened as a kind of bug...

i've changed the functions+variable regex to the following expression to match utf8 chars:

```js
// variables
{
    regex: /\$[^\s=;()]+/gim,
    type: 'k7'
},

// global function calls
{
    regex: /\b([^\s(]+)\s*\(/gm,
    type: 'm0'
},
```
