### ISSUE TITLE
Problem with some comments in  JavaScript

### ISSUE THREAD

**Issue by EWalkerDev** [EnlighterJS/EnlighterJS#121]
The following comments are not parsed correctly 
`//<!Module:{wFramework:'wDevGx',wProject:'bb',wCreateDate:'2020/07/19-17:48:52'}!>`

will become
`//<!--Module:{wFramework:'wDevGx',wProject:'bb',wCreateDate:'2020/07/19-17:48:52'}!-->`
(note the "--" wrongly added at start and end of the comment)

` //<editor-fold "_gx_imports">`
will become

` //<editor-fold "_gx_imports"="">`
(note the '="' wrongly added at the end)

**Comment by AndiDittrich** [comment]
Hi @EWalkerDev 

you've forgot to escape the html specialchars

![image](https://user-images.githubusercontent.com/1474107/87879615-555f5f80-c9ec-11ea-89b8-cd1fe7669696.png)
