### ISSUE TITLE
Scroll to highlighted line

### ISSUE THREAD

**Issue by ajinabraham** [EnlighterJS/EnlighterJS#122]
Consider a code block with 5000 lines and line number 3000 is the highlighted line. Does EnlightJS provide a feature where once the page gets loaded, it will automatically scroll down so that the highlight on line 3000 is visible to the user without manual scrolling? Is this feature already available? Couldn't find anything in the docs.

**Comment by AndiDittrich** [comment]
i would say... your method using code snippets is "wrong"

by displaying such large files every visitor will immediately leave your website. normally you extract a short snippet (20...100) lines and highlight special lines of codes which matches the outer description of the post/page

**Comment by ajinabraham** [comment]
My use case is slightly different. My application has a code browser that uses EnlightJS to format the source code and show highlighted line numbers similar to that of Github. This is my current hack to achieve scrolling to highlighted lines

`document.getElementsByClassName("enlighter-special")[0].scrollIntoView();`

**Comment by AndiDittrich** [comment]
that's already the perfect solution. an internal implementation would exactly look like this.
