### ISSUE TITLE
Markdown Syntax Highlight

### ISSUE THREAD

**Issue by slouge** [EnlighterJS/EnlighterJS#128]
I have a problem to make Markdown code Highlighting in Wordpress Guntenberg editor.
The MD code is highlighted but not rendered like bold, lists, code, etc.
Did i miss a configuration ?
![image](https://user-images.githubusercontent.com/12211604/90133406-b3732e80-dd6f-11ea-8e2b-ce56f95f08ff.png)

**Comment by AndiDittrich** [comment]
what do you want to achieve ? highlighting of existing markdown code ?

**Comment by slouge** [comment]
Yes exactly highlighting the markdown (on wordress using you wonderfull plugin !), like that  :

**Test**
- 1
- 2
- 3

```csharp
public class Test
{
 
}
```

**Comment by AndiDittrich** [comment]
Enlighter is a syntax highlighter and not a markdown renderer.

it can only render fenced codeblocks

**Comment by slouge** [comment]
Ok i understand :)
