### ISSUE TITLE
Add success message to copy button

### ISSUE THREAD

**Issue by AndiDittrich** [EnlighterJS/EnlighterJS#130]
**Feature**

* Add a success or failure message to the copy button (and others)

**Requirement**

* Add css based tooltips to the UI components
* Add tooltip support to all themes

**Comment by isc-rsingh** [comment]
Any time frame on this? In our user testing of some coding tutorials (e.g. https://gettingstarted.intersystems.com/full-stack/) this is something every one of our testers were expecting. Thanks for the great highlighter!

**Comment by AndiDittrich** [comment]
![copy-to-clipboard](https://user-images.githubusercontent.com/1474107/196426655-97a2029e-08fe-4c2c-bd46-b867370f9c19.gif)

added to EnlighterJS v3.6.0

**Comment by mrdexters1** [comment]
Hello @AndiDittrich where can I download the new version 3.6.0?
Thank you!

**Comment by AndiDittrich** [comment]
`dist/` dir within master branch
