### ISSUE TITLE
C# language missing keywords

### ISSUE THREAD

**Issue by vladimir-pecanac-main** [EnlighterJS/EnlighterJS#131]
Missing built-in types keywords:

- string
- DateTime

.NET types, but should be interpreted by C# in the editor:

- String - different than string
- Object - different than object
- Int16
- Int32
- Int64
- UInt16
- UInt32
- UInt64
- Double - different than double
- Single
- Decimal - different than decimal
- Char - different than char
- SByte
- Byte - different than byte
- Boolean

Reference:
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/built-in-types

**Comment by vladimir-pecanac-main** [comment]
Examples:

![image](https://user-images.githubusercontent.com/8477856/91904032-85b14380-eca4-11ea-8acb-b5cbd87d181d.png)

**Comment by AndiDittrich** [comment]
HI @vladimir-pecanac-main 

thanks for your input.

of course, `string` is missing in the typelist but the other ones are "highlevel" object wrapper derived from [System.ValueType](https://docs.microsoft.com/de-de/dotnet/api/system.valuetype?view=netcore-3.1) and no basic types.
