### ISSUE TITLE
Characters added when rendering JSX

### ISSUE THREAD

**Issue by german-alvarez-dev** [EnlighterJS/EnlighterJS#133]
I have this JSX snippet:

```
<pre data-enlighter-language="js" class="lang:js decode:true" title="Whatever">

const Warning = Alert => props => <Alert {...props} style={{ color: 'red' }}/>

</pre> 
```

Thant renders as seen here:

```
const Warning = Alert => props => <alert {...props}="" style="{{" color:="" 'red'="" }}="">
</alert>
```

I have tried changing the language to jsx, or even raw with no success.

**Comment by AndiDittrich** [comment]
don't forget to use html escape sequences...

**Comment by german-alvarez-dev** [comment]
> don't forget to use html escape sequences...

Can you provide me of an example @AndiDittrich ? Until now I have just used it for plain JS and never needed to escape anything inside. Thank you.

**Comment by german-alvarez-dev** [comment]
Escaping sequences solved this:

<pre data-enlighter-language="js" class="lang:js decode:true">

const Warning = Alert => props => &lt;Alert {...props} style={{ color: 'red' }}/&gt;

</pre>
