### ISSUE TITLE
No default jsDelivr CDN file set

### ISSUE THREAD

**Issue by duckscofield** [EnlighterJS/EnlighterJS#134]
[This package](https://www.jsdelivr.com/package/npm/enlighterjs) doesn't have a [default file](https://www.jsdelivr.com/features#publishing-packages) set. You can set it via `jsdelivr`, `browser`, or `main` field in `package.json`

**Comment by AndiDittrich** [comment]
due to GDPR in europe, the use CDNs isn't very useful anymore

btw. jsdelivr includes the outdated v2 branch which is not longer maintained

**Comment by PrzemyslawKlys** [comment]
I wouldn't say it's not useful anymore. Plenty of people use it. Would it be possible to publish it anyway for those that want to use it from an officially maintained source

For example my https://github.com/EvotecIT/PSWriteHTML project, which uses your library, is run locally by users, and for now when they want to use "online" version I need to host it on my website for them which is far from optimal. 

As a side note: Not sure how CDN's in Europe are supposed to have problems now? Can you elaborate on this?

**Comment by AndiDittrich** [comment]
i understand your issue but the v2 branch won't receive any maintenance - especially the npm package will be updated to enlighterjs v3 soon.

**Comment by PrzemyslawKlys** [comment]
I don't want v2. I want v3 :-) Current version on CDN ;)

**Comment by AndiDittrich** [comment]
oh you just want an update/publish of the npm package

**Comment by AndiDittrich** [comment]
https://www.npmjs.com/package/enlighterjs

**Comment by PrzemyslawKlys** [comment]
Baasically instead of using my private server which isn't really great for this kind of hosting I would prefer CDN version.

```html
<!-- CSS EnlighterJS CodeBlocks START -->
        <link href="https://evotec.xyz/wp-content/uploads/pswritehtml/enlighterjs30/enlighterjs.min.css" type="text/css" rel="stylesheet" /><!-- CSS EnlighterJS CodeBlocks END -->
        <!-- JS EnlighterJS CodeBlocks START -->
        <script src="https://evotec.xyz/wp-content/uploads/pswritehtml/enlighterjs30/enlighterjs.min.js" type="text/javascript"></script><!-- JS EnlighterJS CodeBlocks END -->
````

Most other libraries:

```html
        <script src="https://code.jquery.com/jquery-3.5.1.min.js" type="text/javascript"></script><!-- JS Jquery END -->
        <!-- CSS OrgChart START -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/orgchart/2.1.3/css/jquery.orgchart.min.css" type="text/css" rel="stylesheet" /><!-- CSS OrgChart END -->
        <!-- JS OrgChart START -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/orgchart/2.1.3/js/jquery.orgchart.min.js" type="text/javascript"></script><!-- JS OrgChart END -->
        <!-- JS ES6Promise START -->
        <script src="https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.auto.min.js" type="text/javascript"></script><!-- JS ES6Promise END -->
        <!-- JS OrgChartExport START -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.5/jspdf.min.js" type="text/javascript"></script><!-- JS OrgChartExport END -->
        <!-- CSS OrgChart START -->
   ````

I don't think NPM will cut it for me.

**Comment by AndiDittrich** [comment]
i didn't know how long the update process of cdnjs will take - it's just a mirror of the npm registry..

**Comment by PrzemyslawKlys** [comment]
Its gettting updated it seems:

![image](https://user-images.githubusercontent.com/15063294/96505599-a6cef300-1256-11eb-91de-09632dc0e8ba.png)

Just not yet. Thank you :)

**Comment by PrzemyslawKlys** [comment]
Whatr about the CSS files?
