### ISSUE TITLE
Installing latest version broken WP installation

### ISSUE THREAD

**Issue by pmanolak** [EnlighterJS/EnlighterJS#135]
A syntax error with the latest version 4.4.0 causing a syntax error:

 `Parse error: syntax error, unexpected ')' in /var/www/html/wp_test/wp-content/plugins/enlighter/modules/core/Enlighter.php on line 98`

**Comment by pmanolak** [comment]
`[Sun Oct 18 16:52:35.776384 2020] [:error] [pid 11992] [client 127.0.0.1:51714] PHP Parse error:  syntax error, unexpected ')' in /var/www/html/wp_test/wp-content/plugins/enlighter/modules/core/Enlighter.php on line 98, referer: http://localhost/wp_test/wp-admin/update.php?action=update-selected&plugins=enlighter%2FEnlighter.php&_wpnonce=afcdec0845
[Sun Oct 18 16:52:48.737561 2020] [:error] [pid 11095] [client 127.0.0.1:51760] PHP Parse error:  syntax error, unexpected ')' in /var/www/html/wp_test/wp-content/plugins/enlighter/modules/core/Enlighter.php on line 98
[Sun Oct 18 16:54:02.508204 2020] [:error] [pid 11196] [client 127.0.0.1:51862] PHP Parse error:  syntax error, unexpected ')' in /var/www/html/wp_test/wp-content/plugins/enlighter/modules/core/Enlighter.php on line 98
[Sun Oct 18 16:54:07.244140 2020] [:error] [pid 31332] [client 127.0.0.1:51864] PHP Parse error:  syntax error, unexpected ')' in /var/www/html/wp_test/wp-content/plugins/enlighter/modules/core/Enlighter.php on line 98
[Sun Oct 18 17:00:55.700532 2020] [:error] [pid 11992] [client 127.0.0.1:52134] PHP Parse error:  syntax error, unexpected ')' in /var/www/html/wp_test/wp-content/plugins/enlighter/modules/core/Enlighter.php on line 98, referer: http://localhost/wp_test/wp-admin/plugin-install.php?s=Enlighter+-+Customizable+Syntax+Highlighter&tab=search&type=term
[Sun Oct 18 17:00:57.283199 2020] [:error] [pid 11992] [client 127.0.0.1:52134] PHP Parse error:  syntax error, unexpected ')' in /var/www/html/wp_test/wp-content/plugins/enlighter/modules/core/Enlighter.php on line 98, referer: http://localhost/wp_test/wp-admin/plugins.php?plugin=enlighter%2FEnlighter.php
[Sun Oct 18 17:00:57.577823 2020] [:error] [pid 4988] [client 127.0.0.1:52162] PHP Parse error:  syntax error, unexpected ')' in /var/www/html/wp_test/wp-content/plugins/enlighter/modules/core/Enlighter.php on line 98, referer: http://localhost/wp_test/wp-admin/plugins.php?plugin=enlighter%2FEnlighter.php
`

**Comment by pmanolak** [comment]
Why this defect closed? Has been fixed? @AndiDittrich

**Comment by AndiDittrich** [comment]
see the changelog in 4.4.1

**Comment by pmanolak** [comment]
Thanks a lot! Missed that.
