### ISSUE TITLE
Consider adding configuration for buttons?

### ISSUE THREAD

**Issue by PrzemyslawKlys** [EnlighterJS/EnlighterJS#136]
I couldn't find a way to enable/disable buttons (sometimes I don't want users to get everything) or to configure how they look in an easy way. For example, I prefer buttons from boostrap4 over the ones in the default theme, but at the same time I want to keep the theme. Maybe a way position buttons as well, as with just one line the positioning isn't perfect. 

![image](https://user-images.githubusercontent.com/15063294/96511261-21037580-125f-11eb-9eca-d115975af104.png)

I tried looking at CSS of themes and I could probably try overwriting styles, but maybe you would consider exposing some configuration as options?

**Comment by AndiDittrich** [comment]
please read the docs: https://github.com/EnlighterJS/documentation/blob/master/Tweaks.md

**Comment by PrzemyslawKlys** [comment]
Sorry :(

**Comment by PrzemyslawKlys** [comment]
Now I know why I asked:

![image](https://user-images.githubusercontent.com/15063294/96512351-a9364a80-1260-11eb-932c-420f1d094426.png)

It seems the code you use is for Less right? How would I use it in CSS? Sorry I'm a bit of noob when it comes to this.

**Comment by AndiDittrich** [comment]
it's all written in less. just concat the selectors : `.enlighter-default .enlighter-btn-raw{`
