### ISSUE TITLE
Code highlighter box is not big enough

### ISSUE THREAD

**Issue by jays1ngh** [EnlighterJS/EnlighterJS#137]
Thank you for developing and sharing this great tool.

On my WordPress blog, the code highlighter box is small and copy feature stays hidden as shown in the picture below when I select Monokai theme. It displays okay when I use Bootstrap4 theme.
![Codehighlighter](https://user-images.githubusercontent.com/72841224/96541201-3aea9a00-12eb-11eb-9775-79aab3288cd0.png)

Your help would be highly appreciated.

Jay

**Comment by AndiDittrich** [comment]
just set a min-height to the inner container or add some margin/paddings.
EnlighterJS block mode is not intended for single line code!

**Comment by AndiDittrich** [comment]
https://github.com/EnlighterJS/documentation/blob/master/Tweaks.md#set-minimal-height-for-single-line-codeblocks

**Comment by jays1ngh** [comment]
Thank you for the documentation link. It helped me and I have fixed the height.
