### ISSUE TITLE
Add language support: JSX

### ISSUE THREAD

**Issue by german-alvarez-dev** [EnlighterJS/EnlighterJS#139]
I have this code:

```
<pre data-enlighter-language="js" class="lang:js decode:true">
  render() {
    return (
        &lt;>
          &lt;h3>{props.title}&lt;/h3>
          &lt;p>{props.detail}&lt;/p>
        &lt;/>
    )
  }
}
</pre>
```

Resulting on this wrong highlighting colors:
<img width="780" alt="Captura de pantalla 2020-11-03 a las 21 50 20" src="https://user-images.githubusercontent.com/46670724/98039189-9ace5e00-1e1e-11eb-966c-ad3b08095777.png">

I have tried many combinations with the symbols, as the shown below, with no success:

```
<pre data-enlighter-language="js" class="lang:js decode:true" >
  render() {
    return (
        &lt;&gt;
          &lt;h3&gt;{props.title}&lt;/h3&gt;
          &lt;p&gt;{props.detail}&lt;/p&gt;
        &lt;/&gt;
    )
  }
}
</pre>
```

Enlighter setup:

```
EnlighterJS.init('pre', 'code', {
            language : 'js',
            indent : 2,
            textOverflow: 'scroll'
        });
```

This does not apply to vainilla JS, just on JSX.

**Comment by AndiDittrich** [comment]
EnlighterJS doesn't support JSX...

**Comment by AndiDittrich** [comment]
i've added a small jsx superset which will parse the xml snippets (but ignores any attributes -> displayed as text). this will avoid rendering errors but it's still no real jsx support
