### ISSUE TITLE
EnlighterJS is displaying all code in one line. It's not breaking lines

### ISSUE THREAD

**Issue by amit-github-personal** [EnlighterJS/EnlighterJS#141]
Hi Team,

I am using enlighter with my vue js application. The issue that I am facing is that the library is not breaking the code for each block of span. 

---
Below you can see the screenshot of the code on page.
[Capture.png](https://postimg.cc/K3nS4Yth)

Please help me with this, I've tried bunch of things nothing seems to be working. I've imported all css and js files in index.html then I am injecting the enlighter.enlight() through a component using javascript like so.

    mounted(){
        let enlighterScript = document.createElement("script");
        enlighterScript.setAttribute("type", "text/javaScript")
        enlighterScript.innerHTML = this.getEnlighterConfig()
        document.body.appendChild(enlighterScript)
        
    },
    methods:{
        getEnlighterConfig(){
            return `EnlighterJS.enlight(document.getElementById('code-block'), {
            language: 'java',
            theme: 'bootstrap4',
            lineoffset: 1,
        });`
        }
    }

This is the html which is in the component

       <div class="code-block" id="code-block">
            @Entity
            @Data
            @NoArgsConstructor
            public class User {
                @Id @GeneratedValue(strategy = GenerationType.AUTO)
                private long id;
                private String firstName;
                private String lastName;
                
            }
        </div>

**Comment by AndiDittrich** [comment]
please post a link to your test site. 

EnlighterJS uses [this method](https://github.com/EnlighterJS/EnlighterJS/blob/master/src/engine/sourcecode-extractor.js) to get the content of an element. you can also check if the issues are already within the components html (before EnlighterJS magic happens)

**Comment by amit-github-personal** [comment]
Okay, I will give you a test code. I don't understand why it doesn't break the lines. It highlights the code of VueJS Component but all code goes like a paragraph.

**Comment by AndiDittrich** [comment]
not a test code... i need a working example page - otherwise i cannot help you
