### ISSUE TITLE
Is there a way to proper highlight HTML code (including CSS & JS Syntax) ?? 

### ISSUE THREAD

**Issue by Neohiro79** [EnlighterJS/EnlighterJS#142]
**Here is the fiddle in question:**

http://jsfiddle.net/neohiro79/zbfdhxjy/7/

Or do I miss some settings or configurations or scripts?

**Comment by Neohiro79** [comment]
Even when using encoded HTML it won't work for either HTML or CSS and JS (switch from class html to generic)

**Class HTML:**
> http://jsfiddle.net/neohiro79/zbfdhxjy/16/

**Class generic:**
> http://jsfiddle.net/neohiro79/zbfdhxjy/15/

**Is there a special classname to enable it for ALL possible HTML languages (such as CSS and Javascript at least) ?**

**Comment by AndiDittrich** [comment]
see https://github.com/EnlighterJS/Plugin.WordPress/issues/73

code-in-code is projected for the pro/enterprise editions

**Comment by Neohiro79** [comment]
Thanx for the quick answer. 

In this case you can close this issue.
