### ISSUE TITLE
EnlighterJS usage with very large sourcecode files

### ISSUE THREAD

**Issue by nuschpl** [EnlighterJS/EnlighterJS#144]
I've got this on console:
`enlighterjs.min.js:formatted:2295 EnlighterJS Internal Error: Error: Infinite tokenizer loop detected; more than 50k tokens - language rule [9] /\b(native|volatile|strictfp|finally|class|static|interface|final|extends|transient|return|throws|public|protected|implements|private|synchronized|default|assert|abstract)\b/g seems to be broken
    at enlighterjs.min.js:formatted:191
    at B.value (enlighterjs.min.js:formatted:230)
    at enlighterjs.min.js:formatted:2189
    at Array.map (<anonymous>)
    at dt (enlighterjs.min.js:formatted:2180)
    at Object._t [as enlight] (enlighterjs.min.js:formatted:2266)
    at Object.success (?md5=3ee4d09014e55b0ee90928cec94b0081&type=java:20070)
    at c (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at l (jquery.min.js:2)`

Unable to provide input, but steps to reproduce:

1. git clone https://github.com/MobSF/Mobile-Security-Framework-MobSF
2. ./run.sh
3. browse http://127.0.0.1:8000
4. upload some complicated Android APK file with lot of code and obfuscation e.g banking apps
5. Click View Source. 
6. JS based code browser which under the hood uses EnlighterJS, code should appear after clicking anything on the left but in my case doesn't with above info as the only message on console

**Comment by AndiDittrich** [comment]
on very large sourcecode snippets these kind of error can occur but is intended by design: it avoids an infinite regex loop caused by invalid regular expressions which blocks or crashes the browser.

**Comment by nuschpl** [comment]
So you mean you don't support those software/users of the library who are aware about that, put a lot of CPU and RAM and decided to go ? If that's the case shouldn't the library just return unprocessed text and warning on console instead of error and blowing off ? There are much more risks to user memory and CPU on standard webpages operating heavily on regex like ads, adblock fighting with those with regexes on every loaded page. Have you done any test confirming that this 50k tokens is appropriate value ? Why not benchmark it runtime, saving number of operations in generic cookie or at least making it configurable by library end user?

**Comment by AndiDittrich** [comment]
if you have special needs, just change the limit within the Tokenizer. We can also add an option to the library which set this limit to a higher value but i would absolutely avoid to allow regular users to use arbitrary values. 
Since you've experience with such large files, it would be great if you can provide a value based on your experiments

just returning text can be a solution but i'm not sure if the current architecture allows this.

and again: the problem is not ram/cpu - the browser crashes due to an infinite loop caused by invalid regular expressions - that's the reason for this hard coded limit.

**Comment by nuschpl** [comment]
It's not caused by CPU bounderies in such simple operation it's about using regexp in way it wastes CPU cycles/. In this case it lools like you are using regex of form (a|b|c|d|e|f|) to search for single occurences of a,b,c,d,e where the distance and sequence of those elements is irrelevant so it's a complete waste to use here regex at all comparing to single cyclic buffer which would go through whole input string and match to those strings "native|volatile|s..." one by one.

**Comment by AndiDittrich** [comment]
if you want to discuss a solution you're welcome but please calm down! 

**this issue is not related to cpu/ram/resource usage**

**Comment by nuschpl** [comment]
Of course it is realated. To match e.g 500th occurrence of those keyboards "native|volatile|strictfp.." regexp  needs to backtrack all 499 previous occurrences  occupying CPU and memory what is a waste comparing to standard search over string, because this loop below can have multiple possible solutions:
![image](https://user-images.githubusercontent.com/4950101/100232878-40aa4f80-2f29-11eb-91dc-2af576cb0612.png)

Please learn how regexps do work internally: http://people.cs.vt.edu/davisjam/downloads/publications/Davis-Dissertation-2020.pdf .

**Comment by AndiDittrich** [comment]
if you have any suggestions for a more performant implementation in javascript just create a pull request and a new issue... i'm not sure about your intention...

regarding you initial issue: is it still an issue or have you removed the internal limit ?

**Comment by AndiDittrich** [comment]
the limit has been changed to 50k per rule. additionally the tokenizer will silently fail and just drops all tokens of the current rule.
