### ISSUE TITLE
Oracle DB/SQL: # in the name is not considered as a string but as  comment 

### ISSUE THREAD

**Issue by petr-hybler** [EnlighterJS/EnlighterJS#145]
Hello .. can you please fix when a column name contains a # symbol, it doesn't mean a comment :) 

for example in 

SELECT *
FROM v$session
WHERE serial# = $1

this will comment out the rest of the line which is not ok ....

thank you

**Comment by AndiDittrich** [comment]
technically it's correct (mysql, mariadb)... you have to put such names in single quotes.

but currently the column name literals are limited to the `\w` character class...

which SQL dialect are you using ? i believe the only reliable solution is to split the sql language support into multiple dialects..

**Comment by petr-hybler** [comment]
it's the Oracle.. I cannot change the naming convention either for this is
a default dictionary provided by Oracle

**Comment by AndiDittrich** [comment]
in this case we need a dedicated "oracle database" language support file. i cannot change it in the generic sql file without breaking a lot of other websites+users.

**Comment by petr-hybler** [comment]
hmm that's right :( I will leave this to you ... if oyu have any free time to fix this, it's fine :) but it's ok to leave it as is

**Comment by AndiDittrich** [comment]
i've split the sql support into multiple subsets/dialects - this should avoid any additional issues in the future. contributions regarding the OracleDB support are welcome 

* Generic SQL
* MariaDB/MySQL
* Oracle Database
* Microsoft SQL Server

see https://github.com/EnlighterJS/EnlighterJS/commit/339ebf862edf8a0c690696a8f0cbac3204e6c501
