### ISSUE TITLE
Plain Text

### ISSUE THREAD

**Issue by DragonHawkAlpha** [EnlighterJS/EnlighterJS#165]
Both plain text and custom styles are not using the raw text settings.  The text keeps coming out black which is not helpful on a grey background.  When set to PHP the '?php' shows in black as do symbols like '='  and ';' and does not relate to any of the customizable theme settings that I can find.

**Comment by AndiDittrich** [comment]
could you please provide an example ?
the issue seems to be related to the ThemeCustomizer or the WordPress plugin ?
