### ISSUE TITLE
There is no bottom scroll bar on mobile and web and the longer codes cannot be readable.

### ISSUE THREAD

**Issue by swtestacademy** [EnlighterJS/EnlighterJS#166]
On mobile and also web there is no bottom scroll bar to see the longer codes.

**Comment by AndiDittrich** [comment]
please provide more informations. with `textOverflow: scroll` it should work as expected https://github.com/EnlighterJS/documentation/blob/master/development/Options.md#textOverflow

**Comment by swtestacademy** [comment]
Here is the link for example: https://www.swtestacademy.com/rest-assured-tutorial-api-testing/

on mobile some longer lines cannot be truncated well and there is no scroll bar. Maybe I am doing sth wrong.

**Comment by swtestacademy** [comment]
My mistake, I have updated the settings and cleared the cache, and re-tried and scroll functionality worked well on my phone.
