### ISSUE TITLE
Not displaying <!doctype html>, <html>, and <head>

### ISSUE THREAD

**Issue by tneilson08** [EnlighterJS/EnlighterJS#167]
When trying to place code with these tags, they are excluded. Also, when `<link>` is used, it will overwrite previous links. For example, I have stylesheets linked in the head. But when linking stylesheets between the pre tags, these stylesheets will overwrite the others if they have the same class names or conflicting styles.

**Comment by AndiDittrich** [comment]
sounds like you've forgot to escape the related html specialchars..

**Comment by tneilson08** [comment]
> sounds like you've forgot to escape the related html specialchars..

What specialchars would they be? I'll give you a shortened version of my code

`
<p>Code to be displayed</p>
<pre data-enlighter-language="html">
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
  <title>NEXTGEN-v3 Standard - Getting Started</title>
  <link rel="stylesheet" href="css/main.css">
</head>

<body>

        <div class="accordion" id="accordionSingleExample">
          <div class="card">
            <div class="card-header-slim white msi-bg-secondary pointer" id="headingOneEx" data-toggle="collapse"
              data-target="#collapseOneEx" aria-expanded="false" aria-controls="collapseOneEx">
              <span class="fw-700 white">Single Accordion</span> | <small class="white">Optional Text</small> <i class="float-right white fa fa-plus"></i>
            </div>
            <div id="collapseOneEx" class="collapse show" aria-labelledby="headingOneEx" data-parent="#accordionSingleExample">
              <div class="card-body no-extra-pad p-3 border">
                
                <h4>Accordion Heading</h4>
                <p>Accordion example text body.</p>
                
              </div>
            </div>
          </div>
        </div>

</body>
</html>
</pre>
`

**Comment by tneilson08** [comment]
Never mind, I figured it out. For anyone who needs it, all angle brackets <> need to be replaced with &lt; for <, and &gt; for >.
Since it worked fine for <div>, <p>, <h1>, etc; I assumed that they weren't needed.

**Comment by AndiDittrich** [comment]
take a look into the mdn docs related to html entities: https://developer.mozilla.org/en-US/docs/Glossary/Entity

most programming languages/frameworks providing build-in escape functions like [php](http://docs.php.net/manual/en/function.htmlspecialchars.php)
