### ISSUE TITLE
Adding padding top and bottom of the code block.

### ISSUE THREAD

**Issue by swtestacademy** [EnlighterJS/EnlighterJS#174]
Hi, 

I tried all I found on the web to add some extra space on top and bottom of the code block but I could not be successful. I am using a customized Dracula theme.

Here is a sample link: https://www.swtestacademy.com/lambda-functions-in-java/

I tried the solution here: https://wordpress.org/support/topic/how-to-add-blank-space-in-the-enlighter-code-box/

I even changed the CSS class to ".enlighter-t-wpcustom" nothing worked. Sth is overriding my CSS settings. I also use !important but not worked as well.

I will be so happy for any help. Also, I could not find any settings about paddings in the customizer menu.

**Comment by swtestacademy** [comment]
I am using also Source Code Pro font by fetching from google font API and here is the CSS of showing google fonts.

.enlighter-t-wpcustom .enlighter span{
font-family: 'Source Code Pro', monospace;
}

Setting the code as Source Code Pro in the drop-down did not work. That's why I used this technique to solve this problem.

**Comment by AndiDittrich** [comment]
Hi @swtestacademy ,

the font-family settings are working as expected, even on your site (i've disabled your rulesets within the element inspector and the font keeps "Source Code Pro".

regarding your initial question: do you want to add space inside (dark bg) or outside (white page pg) of the EnlighterJS container ?

**Comment by swtestacademy** [comment]
Hi Andi,

I have solved my problem by using the below custom CSS to add extra paddings only for the bottom and top of the codes.

.enlighter-default.enlighter-v-standard.enlighter-t-wpcustom.enlighter-overflow-scroll{
	border-top:10px solid #272A36; 
	border-bottom:10px solid #272A36;
}

Maybe there are smarter solutions available but this CSS somehow solved my pain. 

If there is an option in the customizer to play with the **inner padding** settings of the "code block", this will be great. 

For the fonts, The Source Code Pro is working as expected but I needed to use again below custom CSS:

.enlighter-t-wpcustom .enlighter span{
font-family: 'Source Code Pro', monospace;
}

and also below <head> hook:

<style>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Source+Code+Pro&display=swap" rel="stylesheet">
</style>

In this way, I achieved to show Source Code Pro fonts on my site. It did not work by just selecting the "Source Code Pro" from the theme customizer dropdown box. Maybe this is a specific problem for my website, theme, and environment.

Thanks,
Onur

**Comment by AndiDittrich** [comment]
there are some technical limitations regarding the margin/padding values especially when background color differs from transparent - therefore these setting is not available within the customer.

**Comment by swtestacademy** [comment]
Thanks @AndiDittrich. I somehow found a workaround with bottom and top border settings.

**Comment by swtestacademy** [comment]
With border this time the scroll did not look good. Do you have any other better solution for this?

**Comment by swtestacademy** [comment]
I did the below solution and worked better than the border. Still open for improvements.

.enlighter-overflow-scroll.enlighter-v-standard{    
	overflow-x: auto;
	word-wrap: normal!important;
	padding-top: 1em;
	padding-bottom: 1em;
	margin: .5em 0;
	background: #272A36;
}
