### ISSUE TITLE
Is it possible to see the "Copied" status when clicking the Copy button?

### ISSUE THREAD

**Issue by swtestacademy** [EnlighterJS/EnlighterJS#179]
Is it possible to see the "Copied" status when clicking the Copy button? 

The copy button works perfectly but it will be nicer to see "copied" or similar status when we click it.

Reference Page: https://www.swtestacademy.com/java-17-features/

Thanks.

**Comment by AndiDittrich** [comment]
duplicate https://github.com/EnlighterJS/EnlighterJS/issues/130
