### ISSUE TITLE
Toggle option for switching on/off Line wrap check

### ISSUE THREAD

**Issue by SRaj1234** [EnlighterJS/EnlighterJS#180]
Hi Team,

With the current implementation for Line wrap it is always turned on. Can you please help in making it customisable by providing the option to toggle line wrap via Enlighter.init() method.

<img width="449" alt="image" src="https://user-images.githubusercontent.com/35132865/139861519-0dff824f-cd41-45c8-b9b3-0678bbba6479.png">

Current behaviour:
<img width="752" alt="image" src="https://user-images.githubusercontent.com/35132865/139860442-e9bf4a1c-6a48-4423-b5df-8aef48159ffc.png">

Expected Behaviour:
![enlighterLineWrap](https://user-images.githubusercontent.com/35132865/139861074-e83c8ac3-4325-42fd-a9c1-080fbe912ef8.gif)

Thanks,
Sonam

**Comment by AndiDittrich** [comment]
please check the [textOverflow](https://github.com/EnlighterJS/documentation/blob/master/development/Options.md#textOverflow) option

**Comment by SRaj1234** [comment]
Hi @AndiDittrich,

Thanks for the solution! But it worked partially as the toolbar is not setting properly when the scroll happens.
<img width="761" alt="image" src="https://user-images.githubusercontent.com/35132865/140024849-b959e64e-61a6-402c-b4fe-a3af82757192.png">

Can you please have a look at this as well?

**Comment by AndiDittrich** [comment]
at the moment, i cannot fix this issue...the "scroll" solution uses a `display: table` workaround to keep the backgrounds steady

**Comment by SRaj1234** [comment]
Thank you for the resolution and prompt response!! Will make of use of the existing functionality for now.
