### ISSUE TITLE
Wrong method highlight in php if it is named «do».

### ISSUE THREAD

**Issue by oleg-dk** [EnlighterJS/EnlighterJS#181]
Wrong method highlight in php if it is named «do».
E.g. in code
```
public static function customAgent()
{
    if (self::setDocumentRoot() === false) {
        self::log('fail to set document root', ['type' => 'error']);
        return '\\'.__METHOD__.'("errUnknownDocRoot");';
    }

    $result = self::do('customAgent');
    $result = self::parseResult($result);
    self::emulatePeriodical();
    return '\\'.__METHOD__.'('.($result ? $result : '').');';
}
```
screenshot: https://i.imgur.com/fDdQvpq.png

It seems that it highlight as reserved word, but not a method.

EnlighterJS Syntax Highlighter 3.5.1

**Comment by AndiDittrich** [comment]
![image](https://user-images.githubusercontent.com/1474107/151655215-232ba897-dd14-443d-8143-3c2b591c6f5d.png)

thanks for your report, has been fixed
