### ISSUE TITLE
multihighlight, for example php+html

### ISSUE THREAD

**Issue by oleg-dk** [EnlighterJS/EnlighterJS#183]
Is it possible to set multihighlight, for example php+html?

```
<div id="<?= $this->getEditAreaId($areaId='editable_area'); ?>"><?php
    $filePath = '/include/collection/delivery.php';
    $APPLICATION->includeFile($filePath, $params=[], $opts=['SHOW_BORDER' => false]);
    $title = 'Изменить';
    $this->addEditAction($areaId, '/bitrix/admin/public_file_edit.php?path='.$filePath, $title);
?></div>
```
screenshot: https://i.imgur.com/0Oioc2L.png

This is how it highlights in sublime https://i.imgur.com/YCbkuNi.png
Php inside html attribute is highlighted. Also html-tag and html-attribute are highlighted.

EnlighterJS Syntax Highlighter 3.5.1

**Comment by AndiDittrich** [comment]
currently not possible, sry

**Comment by oleg-dk** [comment]
And there is no hope that it will be possible in the future, someday?

**Comment by AndiDittrich** [comment]
it's projected for some kind of pro/enterprise editions in the future

**Comment by oleg-dk** [comment]
thanks for answering
