### ISSUE TITLE
Stripping the left indenting

### ISSUE THREAD

**Issue by ajtruckle** [EnlighterJS/EnlighterJS#187]
Hi!

Please see:

https://www.publictalksoftware.co.uk/2022/02/meeting-schedule-assistant-version-22-0-3-newsletter/

In bbPress topics I am used to the codeblocks stripping the left whitespace. But in Gutenberg this did not happen? Should it? Do I have an issue on the site?

**Comment by ajtruckle** [comment]
Also, is there any way for me to add a code block to a comment at bottom of post? (the above link)

**Comment by AndiDittrich** [comment]
i cannot see any bbPress content on the link.
which shortcode renderer do you use ?

**Comment by ajtruckle** [comment]
Sorry if I confuse you.

What I am saying is that when I do bbPress posts, the TinyMCE approach it has a **Left-align Indentation** option:

![Indent](https://user-images.githubusercontent.com/7985331/153055533-efc3ef22-1129-44a1-8011-f28287fdcd79.png)

Once you click OK the code is left indented:

![Indent2](https://user-images.githubusercontent.com/7985331/153055594-7884cede-058f-4ea9-9197-429b1da935b9.png)

But when using Gutenberg with a post (like my link in original comment), if offers no such feature:

![gutenberg1](https://user-images.githubusercontent.com/7985331/153055998-8d3784b5-fd6e-4a31-9ede-4e8e30d5ffcf.png)

The code was exactly the same. But no evident option for left-align indent. So when I preview the post:

![Gutenberg2](https://user-images.githubusercontent.com/7985331/153056111-d36fceaa-f8af-4c2d-bb0c-0f66559a4c8f.png)

Does that make sense?

**Comment by AndiDittrich** [comment]
both plugins (TinyMCE and Gutenberg) are totally different in usage - therefore not all "addon" options (which are not part of EnlighterJS) are shared inbetween.

**Comment by ajtruckle** [comment]
I understand. But it is a great option. Can it please be considered as a feature request? Not to worry if not.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by AndiDittrich** [comment]
https://github.com/EnlighterJS/Plugin.Gutenberg/issues/35

**Comment by AndiDittrich** [comment]
feature has been added to EnlighterJS.Gutenberg v1.2.0
