### ISSUE TITLE
How to select overlapping alternatives?

### ISSUE THREAD

**Issue by twhitehead** [EnlighterJS/EnlighterJS#189]
The main page says to use github for questions,  Hopefully that means to open as issue as there is no discussions tab. Apologies if this is not what was intended.

We want to highlight code both of the form
```
<synhi> ... <pre>
  ...
</synhi> ... </pre>
```
and
```
<synhi> ... <pre><code>
  ...
</synhi> ... </pre></code>
```
but I can't seem to specify a selector that does both of these properly.

Examples that I have tried include trying to combine the selectors for the individual cases

* `synhi pre > code, synhi pre`
* `synhi pre, synhi pre > code`

but they both just match the shorter `synhi pre` selector and leave visible `<code> ... </code>` wrappers for the longer `synhi pre > code`.

I have also tried various pseudo selectors with no luck. Any advice would be really appreciated. Thanks!

**Comment by AndiDittrich** [comment]
for such cases you may need to call the `EnlighterJS.init` function twice with different selectors - see https://github.com/EnlighterJS/EnlighterJS/blob/master/src/browser/EnlighterJS.js#L82 for details.

the `_dom.getElements` call is just a wrapper around Document.querySelectorAll() - see https://github.com/npkgz/dom-magic/blob/master/lib/element.js#L23

**Comment by twhitehead** [comment]
That is very helpful. Thanks very much!
