### ISSUE TITLE
Bad button positioning in {one, two & three}-line code block

### ISSUE THREAD

**Issue by oleg-dk** [EnlighterJS/EnlighterJS#197]
The buttons get up in the wrong position, in a one-line code block:
![Firefox_Screenshot_2022-08-10T15-49-16 732Z](https://user-images.githubusercontent.com/54641461/183952659-3af08c10-1bb3-45a9-b893-b01f06fd661e.png)
two-line code block:
![Firefox_Screenshot_2022-08-10T15-56-05 688Z](https://user-images.githubusercontent.com/54641461/183955825-2dcf4ed9-a74a-44e9-9c91-0f17e1f875d7.png)
and even three-line block doesn't looks good:
![Firefox_Screenshot_2022-08-10T15-59-17 531Z](https://user-images.githubusercontent.com/54641461/183957050-8db1bc9d-2854-4a9a-b5af-a50fd963df2a.png)

**Comment by AndiDittrich** [comment]
see https://github.com/EnlighterJS/documentation/blob/master/Tweaks.md#set-minimal-height-for-single-line-codeblocks for specific css code.

there are not plans to change this behaviour because the toolbar can be moved to different positions
