### ISSUE TITLE
Problem with styling around enlighter block

### ISSUE THREAD

**Issue by oleg-dk** [EnlighterJS/EnlighterJS#198]
There is the problem in styling page around enlighter block. It has margin under it:
![Firefox_Screenshot_2022-08-10T16-12-21 116Z](https://user-images.githubusercontent.com/54641461/183960369-4a2b8cb1-6a53-4f09-8999-6c9726f583f9.png)
it may be ok… but if i want the text to go right behind it, for example in case:

> To see the privileges, enter the command:
> `SHOW GRANTS FOR bitrix0@localhost;`
> where instead of `bitrix0` you need to specify the username, and instead of `localhost` – the hostname.

i fail to do it, because in html dom enlighter div-tag stands before the original pre-tag
![Firefox_Screenshot_2022-08-10T16-25-34 416Z](https://user-images.githubusercontent.com/54641461/183962926-ee7087ae-44f1-4da8-8828-2d3f95405d3a.png)
so i even can't slyle it with css rule
`.enlighter-origin.no-bottom-margin + .enlighter-default { margin-bottom: 0; }`

My sugesstion is to add enlighter div-tag after original pre-tag, so we can style bottom-margin. Or think about a way of forwarding classes from original pre-tag to enlighter div-tag.

**Comment by AndiDittrich** [comment]
if i understand your issue correctly: you want to remove the margin from specific blocks ? there are 2 solutions available

1. create a custom theme
2. enable [retainCssClasses](https://github.com/EnlighterJS/EnlighterJS/blob/master/src/engine/options.js#L37) option to copy all classes of the `pre` wrapper to the enlighter codeblocks. this allows you to add a custom class which removes the margin

**Comment by oleg-dk** [comment]
Yep, thanks.
2nd is just what i need.
