### ISSUE TITLE
AMP Compatibility

### ISSUE THREAD

**Issue by HarmVeenstra** [EnlighterJS/EnlighterJS#199]
![image](https://user-images.githubusercontent.com/5159742/188506652-2d34cfde-ce07-4fdf-a9c2-fbf2170e1cce.png)

**Comment by AndiDittrich** [comment]
please take a look into the amp docs regarding external javascripts

**Comment by HarmVeenstra** [comment]
Uhm, ok? Not sure what you mean, can I fix this myself? I'm using EnlighterJS for my page to show PowerShell Scripts in

**Comment by AndiDittrich** [comment]
no you can't... i wouldn't recommend to use amp ...

see https://amp.dev/documentation/guides-and-tutorials/develop/custom-javascript/

**Comment by HarmVeenstra** [comment]
Thanks for your input, trying everything now without AMP enabled.
