### ISSUE TITLE
Add copy button

### ISSUE THREAD

**Issue by Noogic** [EnlighterJS/EnlighterJS#2]
It would be great if, on hover, it displays some little button to copy the code. 

Actually it's impossible to copy the code except going line by line.

**Comment by judasane** [comment]
That link doesn't work, And we're now in 2019. Some advances here?

**Comment by AndiDittrich** [comment]
the copy function has been added to [EnlighterJS v3](https://github.com/EnlighterJS/EnlighterJS/releases)
