### ISSUE TITLE
Bash syntax highlighter renders $# incorrectly as the beginning of a comment

### ISSUE THREAD

**Issue by maidentaiwan** [EnlighterJS/EnlighterJS#200]
**Describe the bug**
Bash syntax highlighter treats $# as the beginning of a comment instead of a variable.

**WordPress Editing Mode**
Classic editor, but it doesn't matter because it's a rendering bug

**Frontend or Backend Issue**
Frontend

**To Reproduce**
See screenshot line 4 for incorrect highlighting.
Use Block-Code, Bash script, Standard (enlighter) settings

**Expected behavior**
The syntax $# should be highlighted like a variable, not like a comment.

**Screenshots**
![Screenshot_20221017_121301](https://user-images.githubusercontent.com/4689691/196229588-dcab0803-e6fc-45b8-936b-88b9e13dfd45.png)

**Example code**
If applicable, add a small code snippet which causes the issue.

```
if [ $# -ne 2]; then
```

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux 18.04 LTS
 - Browser Chrome
 - Version 106.0.5249.119 (Official Build) (64-bit)

**Comment by AndiDittrich** [comment]
thanks, fixed in 3.5.1
