### ISSUE TITLE
Can we easily amend the  inline styles

### ISSUE THREAD

**Issue by westerdaled** [EnlighterJS/EnlighterJS#205]
I am thinking of removing the border and perhaps change the font size as viewed in my recent post.

![image](https://user-images.githubusercontent.com/937208/205449036-31e47d52-f2d3-418d-b741-d32960273f1e.png)

**Comment by AndiDittrich** [comment]
just tweak your custom theme : https://github.com/EnlighterJS/EnlighterJS/blob/master/src/themes/enlighter.less#L332

**Comment by westerdaled** [comment]
Ah I thanks for the reply. I see the class I need to tweak. I think I can change the styles via the plugin settings page. Can you please confirm.

**Comment by AndiDittrich** [comment]
not possible
