### ISSUE TITLE
Selecting tab in all codegroups

### ISSUE THREAD

**Issue by marcinjakubowski** [EnlighterJS/EnlighterJS#21]
Is there a way to make EJS select the same tab (either by its name or index, both would work for me) in all code groups when one of them is selected?

Imagine I have several snippets, each in a code group, and a tab represent code in a given language, e.g. either JavaScript or C#. Whenever a user selects C# tab, it means they want to see the C# code in all of the code groups, so I would like to automatically switch to the C# tab in all of them.

Example (using WordPress notation):

```
[codegroup]
   [js tab="Javascript"]// javascript code, part 1[/js]
   [csharp tab="C#"]// C# code, part 1[/csharp]
[/codegroup]

[codegroup]
   [js tab="Javascript"]// javascript code, part 2[/js]
   [csharp tab="C#"]// C# code, part 2[/csharp]
[/codegroup]
```

I suppose there is no such built-in feature, so I would be very grateful for a code snippet (I'm not at all familiar with Moo).

**Comment by AndiDittrich** [comment]
Dear Marcin,

such feature requires some internal changes - currently each tab-group is isolated and doesn't use a global event bus or something like this. therefore it is not easy to implement.

at the moment i'm working heavily on EnlighterJS v3 with a new codebase - i will try to add such feature to the new version.

best regards, Andi

**Comment by marcinjakubowski** [comment]
Hi Andi,

Thanks a lot for considering it, though I doubt many people will actually need this, so I wouldn't spend too much time on making it work.

In case someone needs something like that, here's a quick and rather dirty method to do it, by cascading the click event on all tabs sharing the same name. Forgive me for what is most likely poor JS code, it's not my area of expertise.

In jQuery:

    $('div.controls li').click(function() { 
        $(this).addClass('selected');
        $('div.controls li:contains("' + $(this).text() + '"):not(.selected)').first().trigger('click'); 
    });

Or in MooTools (`addClass('selected')` seems not to be required because the normal click event from EJS is fired prior to this new one, but I'm not sure if the order is guaranteed):

    document.getElements('div.controls li').addEvent('click', function() {
        this.addClass('selected');
        var e = document.getElement('div.controls li:contains("' + this.get('text') + '"):not(.selected)');
        e && e.click();
    });

Great work on EJS by the way!

Cheers,
Marcin
