### ISSUE TITLE
How to overwrite styles based on the selected Language

### ISSUE THREAD

**Issue by inimist** [EnlighterJS/EnlighterJS#212]
I am using Enlighter – Customizable Syntax Highlighter on [my blog ](https://devarticles.in/how-to-add-or-remove-cached-git-credentials-on-linux-server-ubuntu/)

On the very page I am using Bash + Bootstrap 4 combination to highlight my code. What I want to do is to style my code to have a dark background and appending a $ symbol to the beginning of first line of the code block. However I am not able to do it since I do not see any class with name "bash" added to any wrapper of the code block.

[Link to screenshot here](https://www.dropbox.com/s/fy5i2nhursuk14n/codeblock.jpg?dl=0)

Can anyone advise how to style the block based on the selection of a particular language?

**Comment by AndiDittrich** [comment]
since v3.6.0 the actual language class is added to the outer wrapper - see https://github.com/EnlighterJS/EnlighterJS/blob/master/CHANGES.md for details

**Comment by inimist** [comment]
Weird. I do not see any `enlighter-l-<resolvedLanguage>` to the wrapper. All I see is `enlighter-default enlighter-v-standard enlighter-t-bootstrap4` in the parent wrapper. `bootstrap4` is the Theme of course.

**Comment by AndiDittrich** [comment]
please check your EnlighterJS version

**Comment by inimist** [comment]
It was 4.3 something and it is 4.6.1  now after updating today. The good thing is that I can see "enlighter-l-shell" added to root wrapper now. Thank you!

**Comment by AndiDittrich** [comment]
keep in mind that we're talking about EnlighterJS and **not** the Enlighter WordPress plugin

**Comment by inimist** [comment]
@AndiDittrich - I see :) 
Probably the previous version of WordPress plugin had an older version of EnlighterJS. Gotcha!
Thanks again!
