### ISSUE TITLE
Help, breaking html tags in pre

### ISSUE THREAD

**Issue by eshimischi** [EnlighterJS/EnlighterJS#217]
Hello, i have
`<pre class="syntax">void
<b>CTasks::AddTags(</b>
&nbsp;ID,
&nbsp;USER_ID,
&nbsp;array arTags
<b>);</b></pre>`

here is the result, 
<img width="396" alt="Screenshot 2023-06-01 at 16 52 36" src="https://github.com/EnlighterJS/EnlighterJS/assets/983201/a5a3fa80-117e-4437-8f9e-9a4ce01903e4">
any ideas how to fix it and make <b>CTasks::AddTags</b> as bold text, for instance

**Comment by eshimischi** [comment]
More example is:
`<pre class="syntax">&lt;?<br />if (CModule::IncludeModule(&quot;tasks&quot;))<br />{<br /><br />    $ID = 1;<br /><br />    if($USER-&gt;IsAdmin())<br />    {<br />       CTasks::Delete($ID);<br />    }<br /><br />}<br />?&gt;</pre>`

<br/> should break the lines, but instead
<img width="914" alt="Screenshot 2023-06-01 at 17 24 52" src="https://github.com/EnlighterJS/EnlighterJS/assets/983201/c8401a9c-62a6-4830-a119-ed065cfdaf20">

**Comment by AndiDittrich** [comment]
Hi @eshimischi 

that's not the way EnlighterJS is working: everything within the wrapper (can be any kind of html container) is handled as source code. changing the code styling has to be done via the themes

**Comment by eshimischi** [comment]
> Hi @eshimischi
> 
> that's not the way EnlighterJS is working: everything within the wrapper (can be any kind of html container) is handled as source code. changing the code styling has to be done via the themes

Hello, thanks for your reply, but perhaps i asked things incorrectly. I do understand that everything within wrapper is treated as source code, but is any way to treat **html tags** as html tags in php code or not?

**Comment by AndiDittrich** [comment]
you cannot use any kind of html markup (including css) within the sourcecode - the tokenizer will handle it as mostly invalid token because it's not part of the language set. this doesn't affect displaying html sourcecode in php

**Comment by eshimischi** [comment]
> you cannot use any kind of html markup (including css) within the sourcecode - the tokenizer will handle it as mostly invalid token because it's not part of the language set. this doesn't affect displaying html sourcecode in php

i see, yes it is invalid in my case
<img width="487" alt="Screenshot 2023-06-02 at 09 39 30" src="https://github.com/EnlighterJS/EnlighterJS/assets/983201/5a23f722-e607-4fde-9cb4-f8f304715b25">

**Comment by AndiDittrich** [comment]
if your attention is to display this part `CTasks::AddTags` as bold text then yes. you have to change the theme style of the related token `m0`

**Comment by eshimischi** [comment]
> if your attention is to display this part `CTasks::AddTags` as bold text then yes. you have to change the theme style of the related token `m0`

i'll remove html markup within php code and in case of `<br>` i'll change it to \r\n instead. Thanks for your reply, again.

**Comment by AndiDittrich** [comment]
linebreaks should be `\n` or `\r\n` - just regular text within the html container

**Comment by eshimischi** [comment]
> linebreaks should be `\n` or `\r\n` - just regular text within the html container

yes, correct, my bad above.
