### ISSUE TITLE
Height of Gutenberg Block

### ISSUE THREAD

**Issue by ajtruckle** [EnlighterJS/EnlighterJS#219]
Please see:

https://www.publictalksoftware.co.uk/2023/07/student-assignment-history-counsel/

How do I limit the height of the Gutenberg block? At the moment it displays all the code. Can I do this from the Gutenberg Editor?

**Comment by AndiDittrich** [comment]
see https://github.com/EnlighterJS/EnlighterJS/issues/87

**Comment by ajtruckle** [comment]
Thank you. 👍
