### ISSUE TITLE
Idea ChatGPT

### ISSUE THREAD

**Issue by sigalou** [EnlighterJS/EnlighterJS#221]
When we query ChatGPT, we get this type of response

![image](https://github.com/EnlighterJS/EnlighterJS/assets/26350534/24b5ea4c-8f83-47eb-b5db-ad0886f3a45c)

When copying/pasting in WordPress, it would be good if in the proposed formats, ChatGPT could be present to respect its syntax.
Thank you, I hope this is useful to you.

**Comment by AndiDittrich** [comment]
sry, i cannot follow you. whats your intention ? it's just a random snippet above?!

**Comment by sigalou** [comment]
sorry my English must not be good.
I use WordPress plugin and dropdown

![image](https://github.com/EnlighterJS/EnlighterJS/assets/26350534/9379c00d-15b8-4aa1-a071-0a50a129a371)

  I wish there was the ChatGPT format to reproduce this format

![image](https://github.com/EnlighterJS/EnlighterJS/assets/26350534/5cc7abda-2294-4594-a312-8ee19cdba624)

when you copy/paste on WordPress.

**Comment by AndiDittrich** [comment]
that's technically not possible. there is no generic "ChatGPT" format
