### ISSUE TITLE
 Issue with Line Breaks in Code Blocks using Enlighter Plugin on Elementor

### ISSUE THREAD

**Issue by lyc233nb** [EnlighterJS/EnlighterJS#227]
Hello [Developer/Support Team],

I hope this message finds you well. I am reaching out to report an issue I’ve encountered while using the Enlighter plugin to display code blocks within Elementor on my WordPress site.

Problem Description:
When I format my code using the Enlighter plugin, it seems to be converted correctly in the text editor. However, upon viewing the page live, the line breaks in my code are replaced with `<br>` tags, disrupting the intended formatting of the code. Here's an example of how my code appears within the Elementor text editor:

```html
<pre class="EnlighterJSRAW" data-enlighter-language="cpp">
/*
* This is a multi-line comment
*/
</pre>
```

Expected Result:
The code should be displayed with proper line breaks and formatting when rendered on the website.

Actual Result:
The rendered code displays `<br>` tags where the line breaks should be, resulting in a cluttered code block.

Troubleshooting Steps Taken:
- I have checked the Enlighter plugin settings for any line breaking/formatting options and adjusted them accordingly, but the issue persists.
- I have made sure not to use the visual editor in Elementor after pasting my code into the text module to avoid any auto-formatting issues.

I am not sure whether this is related to a CSS conflict, JavaScript issue, or a misconfiguration within the plugin or Elementor. I would greatly appreciate any guidance or assistance you could provide in resolving this matter. Furthermore, if there is any additional information or access required to diagnose this issue, please let me know, and I'll be happy to comply.

Thank you for your time and assistance.

Best regards, 
Yuchen Lu

**Comment by AndiDittrich** [comment]
duplicate https://github.com/EnlighterJS/Plugin.WordPress/issues/380
