### ISSUE TITLE
Support more languages

### ISSUE THREAD

**Issue by psluke** [EnlighterJS/EnlighterJS#23]
Any chance to support M$ PowerShell and VBScript in one of the next releases?

**Comment by AndiDittrich** [comment]
In v3.0 or 3.1 :)

**Comment by savurself11** [comment]
please support Golang, too.=)

**Comment by AndiDittrich** [comment]
of course!

**Comment by savurself11** [comment]
Thank you so much =)

**Comment by AndiDittrich** [comment]
[Go](https://golang.org/) language support is ready :)
![enlighterjs_golang](https://cloud.githubusercontent.com/assets/1474107/16712821/d765a78c-4692-11e6-8358-8e9fa835061d.jpg)

**Comment by AndiDittrich** [comment]
Powershell experimental support is added to v3.0

![enlighterjs_powershell](https://cloud.githubusercontent.com/assets/1474107/16713225/e460a6e0-46a0-11e6-8877-dab2c502b6ca.jpg)

**Comment by AndiDittrich** [comment]
VisualBasic NET and Classic are added:
![enlighterjs_vb_net](https://cloud.githubusercontent.com/assets/1474107/16714415/722423dc-46c2-11e6-8162-6606f91454a9.jpg)

**Comment by AndiDittrich** [comment]
look here https://github.com/AndiDittrich/WordPress.Enlighter/issues/37

but i think i can add a special R highlighting set to v3

**Comment by pat-s** [comment]
@AndiDittrich Any rough plans when R support/v3 will be available? Right now we´re using your script on our wordpress site with a lot of R code ([http://www.neo.uni-jena.de/2016/11/01/polygon-fishnet-with-custom-rowcolumn-count/](http://www.neo.uni-jena.de/2016/11/01/polygon-fishnet-with-custom-rowcolumn-count/) - It would be really cool to have R support in the near future :)

**Comment by AndiDittrich** [comment]
I hope i can release v3 in Q1-2017.

The biggest problem on creating new language support files are demo/language example files which cover all possible language syntax elements. 

if you like to contribute you may can create such demo file like http://enlighterjs.org/v3/golang.html

**Comment by ramlez** [comment]
I'd love to see support for Typescript ;)

**Comment by zacol** [comment]
Definitely Typescript and JavaScript (ES6 and newer).

**Comment by zacol** [comment]
Then Sass and SCSS don't work well with the latest version. It has a problem with this code:

`.parent {
    color: #000;
    background: #ccc;

    &--child-one {
        color: #4e4e4e;
    }

    &--child-two {
        color: #g5g5g5;
    }
}`

**Comment by AndiDittrich** [comment]
@zacol EnlighterJS v3 is not released yet. it is currently only available as closed beta.

**Comment by zacol** [comment]
Sorry 👍

**Comment by enbandari** [comment]
Please support Kotlin ~~

**Comment by audioscavenger** [comment]
Thank you!
any chance to see MS-DOS one day?

**Comment by AndiDittrich** [comment]
ms-dos, seriously ? it's not a real "language"...

**Comment by audioscavenger** [comment]
shell is not a real language either however it's in the list

**Comment by AndiDittrich** [comment]
shell/bash are full featured scripting languages. ms-dos isn't.

maybe you mean dos compatible "batch/bat" files ?

**Comment by audioscavenger** [comment]
dos compatible "batch/bat" files are used in Windows. Every versions. Windows 10, yes too. You can say it's "compatible" but I think it's just semantic. The command interpreter changed from command.com to cmd.exe but the language didn't change. It's still MS-DOS or just DOS, whatever you call it :)
I realize it's confusing. Sorry for the confusion.
Anyway, I modified the EnlighterJS.min.js directly and added the necessary code. 
I understand that I should create a dos.js to pull a request but it's too much time to translate the js back to the dev js you use to generate the script as you do not seem to be interested that much. Whatever, thanks for the plugin, I can live with not sharing my work.

**Comment by AndiDittrich** [comment]
sry, it was not meant in a bad way! but creating a reliable langage support file requires very detailed information what it should fulfill.

we can add windows batch file support in the future :)

**Comment by audioscavenger** [comment]
same here, sorry for my language. I created a pull request from the fork I made. Let me know if i need to add more information or more files to the build. It's tested and working, you can check it here: http://www.blog.derewonko.com/technology/digital-image/image-processing/meme-generator-imagemagick/#windows-batch-script-to-automate-meme-generation

**Comment by brianekins** [comment]
@AndiDittrich, Almost 2 years ago you announced that you had added support for Visual Basic.  Did this ever make it into a released version?  I'm not seeing it in the version I got through WordPress and I wasn't able to find language support definition for it in the source either.

**Comment by AndiDittrich** [comment]
EnlighterJS v3 is not release yet, sry
50% of the themes are missing - everything else has been finished :(

**Comment by audioscavenger** [comment]
Good@! keep up the good work@
@brianekins You could do as I did, take some of your own time and pull a request with modified files with your language. It didn't took me much time to understand how to find out which file to update, properly modify the code, pull the request, but the overall process takes some time I must confess. 
This way you can help yourself, and help the community.
And to go faster, peak at the keywords used in another dev that does the same job ;) I peaked at Highlighter.js... It helped aloooot. I shouldn't admit such an embarrassment I know ;)

**Comment by Alnahrawy** [comment]
> VisualBasic NET and Classic are added:

No .. it is not.

**Comment by AndiDittrich** [comment]
it is.... https://github.com/EnlighterJS/EnlighterJS/blob/master/src/lang/visual-basic.js
