### ISSUE TITLE
Add more themes

### ISSUE THREAD

**Issue by pat-s** [EnlighterJS/EnlighterJS#24]
For example, my favorite dark theme -> https://draculatheme.com

**Comment by zenorocha** [comment]
Thanks for suggesting Dracula @pat-s!

**Comment by AndiDittrich** [comment]
## Dracula Theme ##
![enlighter_dracula](https://user-images.githubusercontent.com/1474107/42633535-129816de-85e1-11e8-80a6-475516bed98e.png)

## Bootstrap 4 Theme ##
![enlighter_bootstrap](https://user-images.githubusercontent.com/1474107/42633546-1c7004aa-85e1-11e8-974e-2f150d736a97.png)
