### ISSUE TITLE
R language support - first steps

### ISSUE THREAD

**Issue by pat-s** [EnlighterJS/EnlighterJS#25]
Dear Andi,

I just created `R.js` with this [commit](https://github.com/pat-s/EnlighterJS/commit/102b2beac81c020d383cd196ea97775984ee7bcb). Besides adding keywords and built-in functions, I do not really know what in detail you need to get things going (although I read your instructions) and how I should implement them. For example, R uses "@" and "$" to address subobjects/columns in S3/S4 class types. Both are frequently used and hence should be recognized correctly.

Also, comparing the list of functions to other languages, I assume the list is way to large? 

Sorry for bothering you with such "tutorial" like questions - if this takes too much time to explain in detail I´ll just wait until you find the time to implement R support - however I would really like to help!

**Comment by AndiDittrich** [comment]
Dear Patrick,

**thanks for your effort!** 

## v2/v3 Incompatibility ##

Generally there is reason i didn't release new languages for a while: EnlighterJS v3 is **incompatible** with v1/v2 - this means all themes and language support files have to be **rewritten**. 
at the moment i have re-created all v2 language files and i'm working on the themes.

this implies that i cannot use your R file in v3 - **but** i will convert it to the new format. therefore i would recommend you to add references to **each syntax element** like the one in your keyword lists:

```
// source: https://stat.ethz.ch/R-manual/R-devel/library/base/html/reserved.html
```

Additionally, it would be **very very very** helpful when you are able to create a detailed R demo file with all used language/syntax elements (like http://enlighterjs.org/v3/golang.html)

## Your Questions ##

* **Functions/Keywords** should be implemented as Regex based on its Syntax - do not use lists
* Take a look on the other languages files like **js** or **python**

best regards, Andi

**Comment by pat-s** [comment]
Thanks for the detailed description @AndiDittrich! I will see what I can do!
