### ISSUE TITLE
JSON blocks are incorrectly formatted in Chrome (v58, macOS)

### ISSUE THREAD

**Issue by cariadeccleston** [EnlighterJS/EnlighterJS#28]
JSON blocks in Chrome v58.0.3029.110 (64-bit) for macOS seem to render a little differently depending on whether a property value is a string containing letters or a string containing numbers.

Given this HTML:
``` html
<pre data-enlighter-language="json">
  {
    "o": {
      "x": "a",
      "y": "b"
    }
  }
</pre>
```
…the "y" is *not* formatted as a property.

However, in this HTML:
``` html
<pre data-enlighter-language="json">
  {
    "o": {
      "x": "1",
      "y": "2"
    }
  }
</pre>
```

…the "y" *is* formatted as a property.

I tried both examples in Safari too, and they both work perfectly. So, I guess it's either a *very* minor incompatibility with Chrome, or Chrome is just broken. If it's Chrome's fault, you can close this with no hard feelings. :grin:

Here's a gist of the HTML I used to test it: https://gist.github.com/cariadeccleston/334c02fbc972f1271ded748a9ac4793e

Here's a screenshot of that HTML file open in Chrome (left) and Safari (right):

<img width="928" alt="screenshot 2017-05-28 20 04 01" src="https://cloud.githubusercontent.com/assets/10532901/26531452/40593974-43e1-11e7-8ec0-4654f88108c1.png">

Thank you! :grin:

**Comment by AndiDittrich** [comment]
Dear Cariad ,

thanks for your report. 
it is a bug within EnlighterJS tokenizer engine. It will be solved with the upcoming v3 release. i cannot fix this behaviour in the current version. sry

similar issue: https://github.com/AndiDittrich/WordPress.Enlighter/issues/42

br, Andi

**Comment by cariadeccleston** [comment]
@AndiDittrich - thanks!

Apologies for not spotting that other bug before I raised this one. And no worries about fixing it in the current version. 

Thanks for all your time and effort on this project -- I love it!

**Comment by nmoinvaz** [comment]
Using this pattern in EJS.Language.json JS class appears to fix the problem for me.

```
strings: {
    pattern: /('[^'\\\r\n]*(?:\\.[^'\\\r\n]*)*'|"[^"\\\r\n]*(?:\\.[^"\\\r\n]*)*")\s*[,\]}]+/gi,
    alias: "st0"
},
```

**Comment by nmoinvaz** [comment]
Thanks!
