### ISSUE TITLE
Can't make multiline comments working for Python

### ISSUE THREAD

**Issue by Threynaud** [EnlighterJS/EnlighterJS#29]
Hi,
First thanks a lot for this plugin, it is amazing and helps me a lot.

I just encounter a problem with multiline comments in Python and tried a lot of different indentations with no success..
Here is a screenshot of my issue: The syntax highlighting is highlighting inside the comment for some reason.. Is there any workaround?
![capture d ecran 2017-06-28 a 21 33 19](https://user-images.githubusercontent.com/13488732/27656511-81cade78-5c49-11e7-9b36-5fd90b69070e.png)

![capture d ecran 2017-06-28 a 21 36 05](https://user-images.githubusercontent.com/13488732/27656605-dce962d4-5c49-11e7-9c8b-9a582d05d201.png)

**Comment by AndiDittrich** [comment]
Hi Threynaud,

that looks weird...normally multiline phyton comments are supported (see https://enlighterjs.org/Language.Python.html). Maybe its a bug within the tokenizer engine.

could you please provide the testcode above ?

br, Andi
