### ISSUE TITLE
Language Support Request: CiscoIOS Config+Terminal Output

### ISSUE THREAD

**Issue by ivanbrens** [EnlighterJS/EnlighterJS#32]
Thanks for creating such an awesome and customizable plugin.  I have a particular use-case where I would like to highlight a specific word or value for a language that is not currently supported.  Specifically, Cisco IOS configuration output or configuration snippets.  I would like to highlight specific words and such, is that currently possible, or can it be added to the plugin?  

I can provide screenshots if needed.

Thanks

**Comment by AndiDittrich** [comment]
Hi Ivan,

you can add a [custom language support file](https://github.com/AndiDittrich/EnlighterJS/blob/master/LanguageDevelopment.html) which exactly meet your requirements (highlighting some words is very simple: just define a list).

i can also add cisco-ios support to EnlighterJS v3 to highlight the config files

best regards, Andi
