### ISSUE TITLE
Support for Cmder's MonoKai

### ISSUE THREAD

**Issue by westerdaled** [EnlighterJS/EnlighterJS#37]
Hi 

Is it possible to set up the above in EnligherJS V3  . My thoughts this could be the default theme for any code I wish to emphasises in a post?

**Comment by AndiDittrich** [comment]
Hi,

do you mean the "Monokai" theme which was originally created for textMate ?

if so, i can add it to the next release (its very similar to dracula)

best regards, Andi

**Comment by westerdaled** [comment]
Andi 

Indeed, I have also set MonoKai to be default theme in VS Code so this enhancement would be welcome ( default Enlighter mark up). Thanks 

Daniel

**Comment by AndiDittrich** [comment]
not as default ;)

**Comment by AndiDittrich** [comment]
![image](https://user-images.githubusercontent.com/1474107/53162323-15643500-35cc-11e9-9d81-504ae0b3cd62.png)

**Comment by westerdaled** [comment]
That is looking good - excellent progress... Notice the top menu is gone. Is that a check box property to toggle hide/ show or is that wishful thinking😉.

**Comment by AndiDittrich** [comment]
please take a look into the [docs](https://github.com/EnlighterJS/docs/blob/master/Tweaks.md) - such option can be set via css

**Comment by westerdaled** [comment]
Yes,  I was hoping something I could set per block item.

**Comment by AndiDittrich** [comment]
use a derived theme for each block

**Comment by westerdaled** [comment]
Yes, as soon as I posted I realised this is what I needed to do. Ok, I am keen to test Monokai and RC2 ,will look at the install docs if they are on here.

**Comment by AndiDittrich** [comment]
there will no additional install docs...everything whats needed is already in place

**Comment by westerdaled** [comment]
Hmmmm I am still using RC1 which I think I manually had to install via FTP   As, I have't been prompted to install via the standard  WordPress Plugin updates, I am guessing I will need to repeat the manual install ( Master or Dev branches.) If so, is this documented anywhere?

**Comment by AndiDittrich** [comment]
https://github.com/EnlighterJS/experiments/tree/master/wp-enlighterjs3-compat

**Comment by westerdaled** [comment]
Ok, Don't need to copy of the themes dir as well as I think these have been refactored?

**Comment by AndiDittrich** [comment]
there is no "themes" dir which requires an update, you just need the following components:

* Enlighter Plugin from WordPress.org registry
* EnlighterJS3 Compat Plugin from [EnlighterJS/experiments](https://github.com/EnlighterJS/experiments/tree/master/wp-enlighterjs3-compat)

and follow the instructions mentioned the compat plugin readme

**Comment by westerdaled** [comment]
Andi 

I have 'followed' your instructions.
Enlighter Plugin already installed and gets updated when updates available ( see attachment)

![enlightner plugins](https://user-images.githubusercontent.com/937208/53410239-1ece1280-39bb-11e9-980a-f480598977f0.PNG)

uploaded EnlighterJS Compact Plugin from your RC2 master branch ( overwrote the previous plugin source)
![enlightener plugin dir](https://user-images.githubusercontent.com/937208/53410270-386f5a00-39bb-11e9-893f-64ed92204d74.PNG)

I would have thought I would enabled the 2nd plugin as RC2 but I am still seeing the Alpha 1. Does this look ok?

**Comment by AndiDittrich** [comment]
it looks ok

**Comment by AndiDittrich** [comment]
it works fine within my testing environment. did you cleared your browser cache ?

**Comment by westerdaled** [comment]
No, but I can do that.

**Comment by westerdaled** [comment]
Yep that did it - looks really good. Well done!  Oh and that annoying top menu is staying nicely hidden. Win win!

**Comment by AndiDittrich** [comment]
great. if you have any problems with the theme please don't hesitate to open a new issue!
