### ISSUE TITLE
toolbar support when editing in Gutenburg 

### ISSUE THREAD

**Issue by westerdaled** [EnlighterJS/EnlighterJS#38]
Hi

At the moment I am switching to Classic Editor ->  Text view to apply any markup to code snippets.  Will there be future support for editing using Gutenburg / WP 5.0 ?

**Comment by AndiDittrich** [comment]
see https://github.com/EnlighterJS/Plugin.Gutenberg

currently there are over 1000 Open Issues with the Gutenberg editor which doesn't allows people to use it in any productive case - i hope they will fix it until the WP 5.0 release...

**Comment by AndiDittrich** [comment]
btw. you can still add a "classic" block within Gutenberg. This allows you to use the current Enlighter.TinyMCE Plugn

**Comment by westerdaled** [comment]
Ok

**Comment by AndiDittrich** [comment]
@westerdaled 

i've just released the [first version](https://github.com/EnlighterJS/Plugin.Gutenberg/releases/tag/v0.2.0) subjected for testing purpose. Block based highlighting is working fine

**I would be happy to receive feedback!**

best regards, Andi

**Comment by westerdaled** [comment]
@AndiDittrich 

No problem .  First, do  I refer to the same install routine for this iteration EnlighterJS 3.0 of  as before to perform an update to the current beta I am running.

**Comment by westerdaled** [comment]
Hi 
. 
Now installed - I see the entry for Enlighter in the "+" menu. Will try it out
