### ISSUE TITLE
Quick Review 

### ISSUE THREAD

**Issue by westerdaled** [EnlighterJS/EnlighterJS#39]
Hi

A couple of things I have found in the drafty draft  post I am currently working on using Gutenburg.

Generic and PowerShell colour schemes look very similar - can this be changed ( be similar to VSCode MonoKai) ) ;-)

No line numbers options does seem show a character on the left

Could start of the code be more offset from top Enlighter menu- I think it is bit confusing for readers

[https://westerdale.blog/?p=627&shareadraft=baba627_5babe7bf5d189](url)

**Comment by westerdaled** [comment]
Hi Andi 

I guess I am getting institutionalised by VSCode lol - I just wanted to test out generic verese a given lanaguage: [https://code.visualstudio.com/docs/getstarted/theme-color-reference](url) . Also I haven't found a way of exporting the MonoKai colours as yet.  It is not the end of the world if this is difficult to change.    I did think the highlighting for TypeScript is impressive tho and this is my direction of travel. 


Also is it possible to to slighly change say the background I want to syntax highlight a gist in whatevery language ( to remind me which bits of code I make public domain) .  will look at the override link when I get a chance. 

Regards

Daniel

**Comment by AndiDittrich** [comment]
the VS Code Monokai colors are available [here](https://github.com/Microsoft/vscode/blob/master/extensions/theme-monokai/themes/monokai-color-theme.json)

you can change the background of the panel as well as of each token - its pure css

**Comment by AndiDittrich** [comment]
**General Color Schemes**

1. just take a [theme of your choice](https://github.com/EnlighterJS/EnlighterJS/tree/master/src/themes) and rename it. 
2. modify the theme
3. finally run `gulp` to build your theme - [developer guide](https://github.com/EnlighterJS/docs/blob/master/DeveloperGuide.md)
4. the token are names and its purpose [are documented](https://github.com/EnlighterJS/docs/blob/master/HighlightingEngine_and_Symbols.md).

**Language Specific Schemes**

EnlighterJS is not designed to create language specific color schemes - its designed to provide the same experience on all given languages. therefore all tokens are used for a special purpose as documented.

**Comment by westerdaled** [comment]
Ok I will have to make  start and pick one of the themes
