### ISSUE TITLE
style advice

### ISSUE THREAD

**Issue by westerdaled** [EnlighterJS/EnlighterJS#40]
hi 

In the attachment I am trying to show commands and the output response. However, I am not sure whether to use Enllighter to format the output response and if so, what you suggest.  Alternatively I could use one of the Gutenberg  block formats.
![enlighter formatting issue](https://user-images.githubusercontent.com/937208/46632924-18dab080-cb44-11e8-81d8-096dd5eeb024.PNG)

Any update on the top Enlighter menu changes btw?

**Comment by AndiDittrich** [comment]
Hi Daniel,

the **generic** mode is not intended to be used with text content. i would recommend you to use the **raw** mode without highlighting.

i didn't have enough time yet to improve to button-bar. adding a large padding is no solution because in most cases the bar will only be visible on hover.

best regards, Andi

**Comment by westerdaled** [comment]
Hi

I thought I would have another go - the bottom block is using the raw mode but unfortunately , I can't really use this - want to make it look like a gist and, or offset that header ;(

![image](https://user-images.githubusercontent.com/937208/51687913-63951100-1feb-11e9-920b-f4a0f3d93eae.png)

Also, can you please confirm I am using the 'latest and greatest'

![image](https://user-images.githubusercontent.com/937208/51688252-18c7c900-1fec-11e9-96b5-93b8f4d39e5c.png)

**Comment by AndiDittrich** [comment]
Hi Daniel,

the "EnlighterJS Gutenberg" development plugin is not longer required - it's added to the Enlighter Plugin as of **v3.8.0**

what do you want to achieve ? maybe you can post an example of your "final style". By using the Chrome developer tools (inspector) you can easily obtain the toolbar css class - remove the absolute positioning and the bar will always appear on the top (set `display:block !important` to disable the hover effect..)

br, Andi

**Comment by westerdaled** [comment]
Hi Andi

Thanks, this is now deleted.

Good question, I guess I want one more styles depending on how complex the code or what effect I am going for

Simple

![image](https://user-images.githubusercontent.com/937208/51691952-c1c5f200-1ff3-11e9-8328-3fbe017f8ad2.png)

Monokai
![image](https://user-images.githubusercontent.com/937208/51692717-6d237680-1ff5-11e9-9a56-2b81e83e9926.png)


A Gist style1
![image](https://user-images.githubusercontent.com/937208/51692289-81b33f00-1ff4-11e9-8d0b-0a7f62b04162.png)

A Gist style2
![image](https://user-images.githubusercontent.com/937208/51692559-14ec7480-1ff5-11e9-8c6c-d685aacb3c5e.png)

As regards the header I want to nuke it only for given post like so like 'Simple' above.  I don't want to override this for the whole plog .  _I think I read somewhere I can add css to a post or page_

**Comment by AndiDittrich** [comment]
you should copy+paste (rename) on of the themes and apply your changes - this allows you to select your "special" theme within the post/page you want without changing the default theme styles

**Comment by westerdaled** [comment]
Hi  this sounds a good approach. Could you please point me at the instructions e,g. ftp onto host site and go to folder x .

**Comment by AndiDittrich** [comment]
1. Download the [EnlighterJS 3.0.0-RC1 Sources](https://github.com/EnlighterJS/EnlighterJS/tree/v3.0.0-RC1/src/themes)
2. clone a theme in `src/themes`
3. rename the theme (filename as well as all classes in the file)
4. modify it to match your needs 
5. add your theme to the `gulpfile.js` theme list
6. rebuild the EnlighterJS css with `./gulp less-themes-full` (`enlighterjs.min.css` is build in `dist/`)
7. replace the file in `wp-enlighterjs3-compat/assets`
8. add your theme to the themelist in `wp-enlighterjs3-compat/wp-enlighterjs3-compat.php`

thats it :)

**Comment by westerdaled** [comment]
Yes, I can have a go at that - will report back. Thanks again.

**Comment by westerdaled** [comment]
Well I have now downloaded the source via the awesome [file fetcher](https://github.com/Gyumeijie/github-files-fetcher) on GIT and created Monkokai.less  ( from enlighter.less)
Any tips on the approach because it doesn't look a trivial task 😒.
Now I need to  retrofit [Monokai](https://github.com/Microsoft/vscode/blob/master/extensions/theme-monokai/themes/monokai-color-theme.json
)

**Comment by AndiDittrich** [comment]
don't spend to much work into it....the whole css/less themes will change in RC2.

generally it is a lot of work to create bullet proof themes...therefore i didn't have time to apply the latest changes to all of them

**Comment by westerdaled** [comment]
Andi

Now I am confused as to do I modify my copy of one of the themes and then have to redo after RC2? _I could do we a guide on what minimal changes to make to get the most impact ._  I want to post snippets of code in my blog. However, I can't reuse Enlighter with small snippets because of the tool bar issue -  yes I can disable it in CSS but that kind of defeats the whole reason for having the plugin 😐 

- Wait for RC2 and 
- paste formatting and code straight from VS Code
- Just use Gist embeds

**Comment by AndiDittrich** [comment]
you should not create a completely new theme like "monokai" at this time.... just apply some minor changes as mentioned above (change the toolbar display style or add a margin/padding)

and of course, this have to be re-done with the final release because the css+html structure will change

using copy+paste from vs studio code or embedded gist is also a reliable method to post sourcecode

**Comment by westerdaled** [comment]
Thanks for the advice.  Yep will do and I will away it the RC2  update.  Still need the roll your own theme guide tho when you are ready 😉

**Comment by AndiDittrich** [comment]
just finished `v3.0.0-RC2` a few minutes ago. now it is **MUCH** easier to develop custom themes - see [dracula](https://github.com/EnlighterJS/EnlighterJS/blob/master/src/themes/dracula.less) for a dark example

**Comment by westerdaled** [comment]
This is good news and yes, the token based approach looks much better. When you release RC2 I will upgrade as per the instructions you listed above for RC1.

**Comment by AndiDittrich** [comment]
RC2 is already out...im currently working on a first monokai theme version ... but there is no official specification available :(

btw. tokens are already used in EnlighterJS v2 as well as v3-RC1....the RC2 rework consists of a bunch of "syntactic sugar" :+1:

**Comment by westerdaled** [comment]
Hi

Glad to hear about the monokai😊 and whilst you in this productive zone, I would also request "Gist" style as this will save me installing another plugin.  I think I'll mix and match depending on if  want to render whole blocks or single lines of code.  

Didn't realise this out - so I need to watch the repo?

Ok do simple download this and  and replace the existing plugin src on my remote host?

[](https://github.com/EnlighterJS/EnlighterJS/tree/v3.0.0-RC2/src/themes)

**Comment by AndiDittrich** [comment]
The monokai theme isn't commited yet because the token <> color definitions are missing

**Comment by AndiDittrich** [comment]
please update the "compat plugin" - it includes the current monokai version: https://github.com/EnlighterJS/experiments/tree/master/wp-enlighterjs3-compat
