### ISSUE TITLE
It si possible to fold/unfold code?

### ISSUE THREAD

**Issue by DavidGRX** [EnlighterJS/EnlighterJS#41]
Dear colleagues:
  congratulations for such a great tool. I'm using it through the wordpress plugin. 
I wonder if it is possible to have a "button" to fold/unfold the code in a webpage with several source code examples. Something like this (suppose the '+' symbol means unfold)

While loops
example 1 + 
example 2 +

For loops 
example 1 + 
example 2 +

Thank you very much in advance

David

**Comment by AndiDittrich** [comment]
Hi @DavidGRX ,

currently this feature is not implemented. you can may use custom javascript code and add it by yourself

best regards, Andi

**Comment by DavidGRX** [comment]
Andi:
  thank you very much for your fast reply!

David
