### ISSUE TITLE
Change attribute "data-enlighter-language" to something else via settings?

### ISSUE THREAD

**Issue by devdave** [EnlighterJS/EnlighterJS#43]
I realize this would have some pretty big consequences to performance as right now it's just a matter of checking for `<pre>` elements posts for enlighter-language in the data attribute but for years I used another syntax highlighting WP plugin that worked like `<pre language="my language"> code here </pre>` and wanted to see if there was a way to support that format?

It's not doom and gloom stuff for me as I can just make a script to walk through my posts looking for pre tags with the "language" attribute but I also wanted to try and make my posts "Future Safer" (TM) by doing something like `<pre data-language="my lang">` versus  enlighter-language.

**Comment by AndiDittrich** [comment]
Hi @devdave ,

that's currently not supported. i would consider to run a simple regex on your dataset to convert it to the standard enlighter format. The same filter can also be used to switch to another syntax highlighter in the future.

generally you could create your own initialization code for EnlighterJS which will use any kind of attribute as language source,

best regards, Andi

**Comment by devdave** [comment]
Thank you for the advice, closing the issue.
