### ISSUE TITLE
Enlighter doesn't appear in reader mode

### ISSUE THREAD

**Issue by jweisman** [EnlighterJS/EnlighterJS#45]
When viewing a page in Reader mode (Safari or Firefox), the Enlighter-highlighted text does not appear. The `pre.EnlighterJSRAW`  has `display: none` and the `ul` doesn't seem to want to display either.

Is this a known issue? Thanks.

**Comment by AndiDittrich** [comment]
Hi @jweisman ,

of course - EnlighterJS is not optimized for screen readers yet.

but this topic is about to going complex - for example - firefox drops the user stylesheet and the Enlighter  code is shown up three times (origin codeblock, enlighter highlighted `li` elements, enlighter raw view).

i've to take a deep dive into the different screen reader implementations of Firefox, Safari and Edge. This will take some time. currently i believe that there is no standard way to add custom styles - maybe this issue cannot be solved in the near future..

best regards, Andi

**Comment by jweisman** [comment]
Thanks for your quick response Andi. Understood that this is a bigger issue.

Just as an FYI- I did take a look at another code highlighter ([SyntaxHighlighter](https://github.com/syntaxhighlighter/syntaxhighlighter)) which seems to work on in Reader modes. It's a different approach (a table with `div`s inside) but it might be worth taking a look at for ideas.

**Comment by AndiDittrich** [comment]
i've tried v3 and v4 of syntaxhighlighter - both of them are **not working** in Firefox reader mode (same issue as EnlighterJS - there is no possibility to add styles..)
