### ISSUE TITLE
Support double quoted strings in MATLAB syntax highlighting

### ISSUE THREAD

**Issue by versionbayjc** [EnlighterJS/EnlighterJS#48]
Right now it seems only single quotes are recognized for strings in MATLAB source code. Since the R2017a release, it is allowed in MATLAB to use double quotes for strings. It would be nice if EnlighterJS could also support this in highlighting MATLAB source code.
For a reference, please see:
https://www.mathworks.com/help/matlab/ref/string.html

**Comment by AndiDittrich** [comment]
thanks for that hint - added to EnlighterJS3

![image](https://user-images.githubusercontent.com/1474107/51846651-49746f00-231a-11e9-96c6-2c6cfbf6a3de.png)
