### ISSUE TITLE
Language Support Request: QML

### ISSUE THREAD

**Issue by JaviBonilla** [EnlighterJS/EnlighterJS#49]
It would be great if QML would be supported. :-)

https://doc.qt.io/qt-5/qtqml-syntax-basics.html

**Comment by AndiDittrich** [comment]
Hi @JaviBonilla ,

will be implemented in EnlighterJS 3.1 or 3.2 

best regards, Andi

**Comment by AndiDittrich** [comment]
![image](https://user-images.githubusercontent.com/1474107/53445014-e4db2b80-3a0f-11e9-815a-b621f90f9c67.png)

https://github.com/EnlighterJS/EnlighterJS/blob/master/src/lang/qml.js
