### ISSUE TITLE
[Question] Why MooTools?

### ISSUE THREAD

**Issue by willstocks-tech** [EnlighterJS/EnlighterJS#50]
Hey @AndiDittrich 

This is just a pure curiosity question (mainly because I'm trying to get into Javascript and trying to learn bits and pieces every day!):

Why did you choose MooTools as the framework to build Enlighter on? Why not vanilla JavaScript (or - at a push, jQuery as it's already included in WP Core)?

MooTools doesn't seem to have been updated in _years_ and there's even talks about deprecation/not using it for new projects (https://github.com/mootools/mootools-core/issues/2798) as well as support seems _fairly_ limited?

It's definitely an interesting framework, just curious as to why that was your framework of choice? :)

**Comment by AndiDittrich** [comment]
@willstocks-tech ,

a several years ago, MooTools was the **only** framework which supports classes/inheritance and was absolute superior compared to jQuery. I've also used MooTools for a lot of commercial projects.

therefore i've chosen a syntax highlighter which was based on MooTools (lighter.js) but there we're a lot of open bugs pending and i needed some special features for my personal blog -> EnlighterJS v1 was created as fork of lighter.js.

The WordPress plugin named **Enlighter** (without trailing JS!) followed in 2013 - formerly build as internal component of my blog (shortcodes only).

Later on the editor plugins for TinyMCE (v1.8 in 2014) and Gutenberg (v3.8 in 2018) were created to avoid shortcode issues and maximize the usability.

and of course..today we have babel/rollup/es6/react and a lot of native methods which didn't require a whole framework like MooTools anymore.

btw: EnlighterJS v3 works as standalone library (no external frameworks are required) and uses state-of-the-art js features

best regards, Andi

**Comment by willstocks-tech** [comment]
Thanks @AndiDittrich - that's some great insight! :)

So does that mean that soon the WP Plugin (v4.0?) will not require MooTools' FrameWork when it migrates over to EnlighterJS v3?

It's incredibly interesting to see how frameworks can quickly be popular, but die off just as quickly! :O

**Comment by AndiDittrich** [comment]
EnlighterJS 3.0.0-RC2 is already available - please take a look on :+1:

**Comment by willstocks-tech** [comment]
Definitely - I'll take a look! 😁 

If you need a WP Plugin beta tester, shout at me - I'm willing to help out!
