### ISSUE TITLE
Add language support: Dart

### ISSUE THREAD

**Issue by graphicbeacon** [EnlighterJS/EnlighterJS#52]
Hi,

Could we have language support for [Dart](https://dartlang.org)?

I'm using the WordPress plugin at https://creativebracket.com

Thanks so much

**Comment by AndiDittrich** [comment]
in 3.1 or 3.2

**Comment by graphicbeacon** [comment]
3.1 please

**Comment by AndiDittrich** [comment]
maybe ;)

**Comment by graphicbeacon** [comment]
Alright, thanks

**Comment by AndiDittrich** [comment]
in the meantime take a look onto the generic highlighting engine ... it's very powerful

![image](https://user-images.githubusercontent.com/1474107/53448605-1fe15d00-3a18-11e9-886a-5567689c6e91.png)

**Comment by graphicbeacon** [comment]
That looks pretty good. What theme is that?

**Comment by AndiDittrich** [comment]
bootstrap4

**Comment by graphicbeacon** [comment]
Cool, I can't find it in the WordPress plugin settings unfortunately. Looking forward to the future update :)

**Comment by AndiDittrich** [comment]
it's an EnlighterJS v3 theme
