### ISSUE TITLE
Kotlin: String templates

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [EnlighterJS/EnlighterJS#54]
In Kotlin we can use String templates, is it possible to format them instead of the string shows its text in only one color?

**Comment by AndiDittrich** [comment]
![image](https://user-images.githubusercontent.com/1474107/85928893-e1301100-b8b0-11ea-8cbc-ca175f80497d.png)

due to performance reasons string templates are generally not fully parsed (avoid tokenizer recursion)
