### ISSUE TITLE
Live Code Editor

### ISSUE THREAD

**Issue by hamzajamil4** [EnlighterJS/EnlighterJS#56]
Sir I Want Live Code Editor like https://www.w3schools.com/html/tryit.asp?filename=tryhtml_default
where visitor's can easily test with their code with live editor

**Comment by AndiDittrich** [comment]
Hi @hamzajamil4 ,

that's not possible with EnlighterJS - it's a pure syntax-highlighter not an editor.

please take a look at cloud9 (formerly ace) editor or codemirror

best regards,
Andi
