### ISSUE TITLE
Can't hide the line numbers

### ISSUE THREAD

**Issue by westerdaled** [EnlighterJS/EnlighterJS#57]
Hi

I have got around to writing a post with Enlighter since the must anticipated MonKai is in play.
Whilst in Gutenberg pasted in  the same snippet using 

- Preformatted  ( just as a comparison)
-Enlighter Beta 2

![Enlighter Plugin Monokai PowerShell](https://user-images.githubusercontent.com/937208/54551369-df855700-49a5-11e9-89cc-90466451425c.PNG)

I still can't seem to loose the line number or offset although neither are set.   Also, I wonder for small sections of code, a gist theme might be less "in your face" than MonoKai - is there a theme in existence or will this need to be added 😉

**Comment by AndiDittrich** [comment]
just disable the line-numbers ?!

**Comment by westerdaled** [comment]
Hmmmmm I tried that already, saved draft ( but not published),  Personally, find the formatting a bit harsh on the eyes, so for this I will want to look at a gist style / theme.

![Enlighter black settings](https://user-images.githubusercontent.com/937208/54606993-25452c80-4a45-11e9-903d-2a498c95834b.PNG)
![Enlighter block user profile settings](https://user-images.githubusercontent.com/937208/54607183-a997af80-4a45-11e9-8b64-069dbd220b4a.PNG)

**Comment by AndiDittrich** [comment]
i'll check this...maybe it's a bug in EnlighterJS3-RC2 or the Gutenberg editor plugin

**Comment by AndiDittrich** [comment]
seems to be an issue within the EnlighterJS3 option handling

**Comment by westerdaled** [comment]
Ah you see!  And you suspected user error 😱

**Comment by AndiDittrich** [comment]
of course, you didn't described in you initial report that it's related to the block/element settings. the global options are working fine ;)

**Comment by AndiDittrich** [comment]
it's fixed in the master branch - attribute based options now always take precedence over js settings. i've also updated the [experimental integration}(https://github.com/EnlighterJS/experiments/tree/master/wp-enlighterjs3-compat)

thanks daniel!
