### ISSUE TITLE
Too many blank lines being added 

### ISSUE THREAD

**Issue by mohitathwani** [EnlighterJS/EnlighterJS#59]
The plug in on my Wordpress web site is messing up the styling. There are too many blank lines being added. This is the same for all EnlighterJS themes.

<img width="720" alt="Screen Shot 2019-03-23 at 3 52 01 PM" src="https://user-images.githubusercontent.com/1278646/54872731-1bddfc00-4d86-11e9-9710-57c431cc38eb.png">

Any ideas how to fix this?

**Comment by mohitathwani** [comment]
Hi,

Here’s a preview link to the article I am workin on: http://mohit.athwani.net/?p=701&preview=1&_ppp=96bf6b5533

Please let me know how I can go about fixing this issue.

Cheers !

**Comment by AndiDittrich** [comment]
the following css rule has to be removed from your css:

```css
.blog-post.single .post-body ol li:not(:last-of-type), .blog-post.single .post-body ul li:not(:last-of-type), .blog-post.page-post .post-body ol li:not(:last-of-type), .blog-post.page-post .post-body ul li:not(:last-of-type) {
    /* margin-bottom: 20px; */
}
```

**screenshot**

see upper right corner
![Screenshot_2019-04-01_16-58-36](https://user-images.githubusercontent.com/1474107/55337678-6efb3180-549f-11e9-8ea1-56f8f46faa73.png)

**Comment by mohitathwani** [comment]
Thank you so much! I will report this to the theme developer and figure out where to inject this css in. Thanks for your help!
