### ISSUE TITLE
Power Shell: String templates

### ISSUE THREAD

**Issue by Ivanseventynine** [EnlighterJS/EnlighterJS#61]
Is it possible to also add the PowerShell code?

**Comment by AndiDittrich** [comment]
can you provide an example/official reference ?

**Comment by carlocardella** [comment]
I'm not sure it's clear enough, but this post shows the default console colors on Windows: https://www.hanselman.com/blog/GetSolarizedAwesomeCommandPromptColorsForVSVSCodeCmdPowerShellAndMore.aspx

**Comment by AndiDittrich** [comment]
@carlocardella 

this doesn't helps - i need the language reference regarding "string templates"

**Comment by carlocardella** [comment]
where can i find a sample so that I understand the format you need?

**Comment by AndiDittrich** [comment]
something like this: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals
or https://docs.python.org/3/library/string.html#template-strings

**Comment by carlocardella** [comment]
I'm not sure where to find that, @TylerLeonhardt do you know?

**Comment by TylerLeonhardt** [comment]
@AndiDittrich in PowerShell, double quotes are "template strings" by default. 

```pwsh
$name = 'Dave'

"Hello $name"
```

This also applies to multi-line here strings:

```
$name = 'Dave'

@"
Hello
$name
"@
```

If you need to evaluate more than just a variable, you do this:

```pwsh
$name = 'Dave'

"is named Dave?: $($name -eq 'Dave')"
```
Results in:
```
is named Dave?: true
```

**Comment by AndiDittrich** [comment]
thanks @TylerLeonhardt 
but i' looking for some kind of official reference - sometimes there are "strange" combinations implemented which are not supported by the standard EnlighterJS powershell support

**Comment by TylerLeonhardt** [comment]
@AndiDittrich here you go https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_quoting_rules?view=powershell-6

**Comment by AndiDittrich** [comment]
@TylerLeonhardt 
thanks, that looks good

**Comment by AndiDittrich** [comment]
![image](https://user-images.githubusercontent.com/1474107/57159701-daaa2480-6de6-11e9-83ba-8b3c57141e3e.png)
