### ISSUE TITLE
Is there an easy way for us to create our own custom languages?

### ISSUE THREAD

**Issue by patchthecode** [EnlighterJS/EnlighterJS#62]
I needed the Swift language added.
Is there an easy way for us to create our own custom languages?

If we can craete our own, then this would make this library very flexible.

**Comment by AndiDittrich** [comment]
swift support has already been added to EnlighterJS v4 - https://github.com/EnlighterJS/EnlighterJS/blob/master/src/lang/swift.js

you can add a custom language at any time. just read the docs and create a related pull request to this repository.

best regards, Andi

**Comment by jnozzi** [comment]
Just a followup to this; the Swift addition does not appear in Plugin.Gutenberg.

**Comment by AndiDittrich** [comment]
@jnozzi 
because your are still using Enlighter v3 - the swift support has been added to EnlighterJS v3 which will be available within **Enlighter v4**

in the meantime...please take a look onto the following experimental integration: https://github.com/EnlighterJS/Plugin.WordPress/issues/171

**Comment by jnozzi** [comment]
@AndiDittrich Oh! Thank you for clarifying. I'm brand new to EnlighterJS as of this morning, know nothing about WordPress plugins, and I suppose I became overwhelmed with information from the whole of the project repository. Sorry for the noise.
