### ISSUE TITLE
PHP syntax: word 'for' is coloured in PHP constant

### ISSUE THREAD

**Issue by JSkalskiSBG** [EnlighterJS/EnlighterJS#63]
As you can see on image, first part of constant 'FORCE_DOMAIN' is blue.
![image](https://user-images.githubusercontent.com/29060100/56882839-19e21980-6a65-11e9-8c82-a36dadfb3f9e.png)

**Comment by AndiDittrich** [comment]
HI @JSkalskiSBG 

please use the latest EnlighterJS (v3) release. the snippet above seems to be created with EnlighterJS v2 which has some issues within its engine.

best regards, Andi

**Comment by JSkalskiSBG** [comment]
@AndiDittrich 
Any plans about updating WP plugin?
I use newest for WP 5.1

From plugin info:

    Enlighter Plugin Version: 3.9.0
    EnlighterJS Version: 2.13.0

**Comment by AndiDittrich** [comment]
use the experimental integration: https://github.com/EnlighterJS/experiments/tree/master/wp-enlighterjs3-compat

EnlighterJS v3 will be integrated into Enlighter v4 WordPress plugin
