### ISSUE TITLE
Please Support SAP ABAP4 Code ,THX.

### ISSUE THREAD

**Issue by NickyShen** [EnlighterJS/EnlighterJS#64]
Is it possible to also add the ABAP4 code?

**Comment by AndiDittrich** [comment]
is the language reference/definition public available ?

**Comment by NickyShen** [comment]
Yes.
please reference this url:
https://help.sap.com/doc/abapdocu_751_index_htm/7.51/en-US/abenabap_words.htm
thx.

Andi Dittrich <notifications@github.com> 于2019年5月1日周三 下午10:04写道：

**Comment by AndiDittrich** [comment]
the keyword list is too long to add all of them to a language support file.
i've tried to just match uppercase words as keywords `/\b[A-Z_][A-Za-z0-9_]*\b/g` but there seems to be a lot of scripts which are also using lowercase variants...

do you have any suggestions ?

**Comment by AndiDittrich** [comment]
![image](https://user-images.githubusercontent.com/1474107/57198864-496ab780-6f78-11e9-9517-4a60dad92917.png)

**Comment by NickyShen** [comment]
I think this should be feasible. We will perform code formatting during the editing process. Usually the recommended settings are keyword capitalization and other lowercase.
thank you!
