### ISSUE TITLE
Add Elixir language support

### ISSUE THREAD

**Issue by nathanchere** [EnlighterJS/EnlighterJS#68]

**Comment by AndiDittrich** [comment]
in v3.1 or v3.2

**Comment by nathanchere** [comment]
? No idea. I didn't realise there was even a 3.0 yet. I'm having a go at this myself anyway based on whatever version is currently master branch.

**Comment by AndiDittrich** [comment]
see https://github.com/EnlighterJS/EnlighterJS/releases
