### ISSUE TITLE
Tex/LaTeX support

### ISSUE THREAD

**Issue by guyru** [EnlighterJS/EnlighterJS#69]
Please add LaTeX / TeX syntax highlighting.

**Comment by AndiDittrich** [comment]
in v3.1 or v3.2

**Comment by thurnherr** [comment]
Also very interested in having LaTeX as a language added. Thanks!

**Comment by AndiDittrich** [comment]
btw.  does anyone of you have suggestions for the highlighting/examples ?

**Comment by guyru** [comment]
PrismJS has LaTeX support, GeSHI as well.

**Comment by AndiDittrich** [comment]
![image](https://user-images.githubusercontent.com/1474107/79860743-786d7980-83d3-11ea-815a-39d1a55314af.png)
