### ISSUE TITLE
EnlighterJS Cuts off 4 digit line numbers

### ISSUE THREAD

**Issue by mssalvatore** [EnlighterJS/EnlighterJS#71]
EnligherJS Version: 3.10.0
Wordpress Version: 5.2.2

EnlighterJS does not provide enough room for 4 (or more) digit line numbers. The Line Offset was set to "3501" as can be seen in the below HTML.

`<ol start="3501" class="hoverEnabled classicEnlighterJS EnlighterJS">`

Below is a screenshot of what is rendered. You can see that the "3" is cut off but "501" remains.
![Screenshot_20190624_010258](https://user-images.githubusercontent.com/19957806/59992937-2c6b7000-961c-11e9-82b1-4eaadc3e001e.png)

**Comment by mssalvatore** [comment]
Hi @AndiDittrich,

Thanks for the quick response. The above CSS resolves the issue, but I'm  a little confused by your response. You state that it's fixed in v3. Wordpress is reporting the version of EnlighterJS as 3.10.0, but I still see this issue.

**Comment by AndiDittrich** [comment]
please keep a closer look to the versioning strings.... EnlighterJS !== Enlighter WordPress Plugin..

**Comment by mssalvatore** [comment]
Aha! Thank you for clarifying. Should I create an issue in https://github.com/EnlighterJS/Plugin.WordPress, or will this just get resolved whenever the plugin upgrades to EnlighterJS v3?

**Comment by AndiDittrich** [comment]
The issue is related to EnlighterJS not the WordPress plugin
(i've moved your issue from the Gutenberg repository to EnlighterJS/EnlighterJS)

EnlighterJS v3 will be added to the next major release of the WordPress Plugin (v4)
