### ISSUE TITLE
Swift code support please

### ISSUE THREAD

**Issue by lukecsmith** [EnlighterJS/EnlighterJS#72]
Would really appreciate support for the Swift programming language with this plugin.  Cannot find Swift amongst any currently maintained syntax highlighters out there.  Generic mode doesnt really do anything to Swift code at present.  Thanks, Luke

**Comment by AndiDittrich** [comment]
see https://github.com/EnlighterJS/Plugin.WordPress/issues/171

Swift support has already been added to EnlighterJS v3 and will be available in the next major release
