### ISSUE TITLE
Add support for vb.net

### ISSUE THREAD

**Issue by stigzler** [EnlighterJS/EnlighterJS#73]
Love this. Could you add vb.net support? I see in the original javascript code that 40 languages are supported including vb.net. How come they all didn't make it into the WP plugin?

**Comment by AndiDittrich** [comment]
Hi @stigzler 

vb support has already been added to EnlighterJS v3.

to use the current version with the WordPress plugin - see https://github.com/EnlighterJS/Plugin.WordPress/issues/171

**Comment by stigzler** [comment]
Brill - thanks.
