### ISSUE TITLE
AMP support

### ISSUE THREAD

**Issue by EvilSpark** [EnlighterJS/EnlighterJS#74]
whenever I enable amp and visit the page, the whole block of code gets vanished. Using latest WordPress. Any idea if this can be fixed? Any idea how to overcome it?

**Comment by AndiDittrich** [comment]
Hi @EvilSpark ,

i need some more informations/context to address the issue:

what do you mean with "AMP" ? a WordPress plugin (there are a lot of them which say they support AMP) or the raw "Google Accelerated Mobile Pages Project" ?

maybe it is an issue related to MooTools....or the initialization of the codeblocks

best regards, Andi

**Comment by AndiDittrich** [comment]
quoted from https://amp.dev/about/how-amp-works

> AMP pages can’t include any author-written JavaScript. Instead of using JavaScript, interactive page features are handled in custom AMP elements. The custom AMP elements may have JavaScript under the hood, but they’re carefully designed to make sure they don’t cause performance degradation.

therefore EnlighterJS cannot work - AMP is designed to analyze and generate a static page. Dynamic elements have to be developed for AMP. This affects all kind of 3rd party plugins which use javascript

**Comment by EvilSpark** [comment]
thx for the info mate. Cheers
