### ISSUE TITLE
Adding Golang language support

### ISSUE THREAD

**Issue by hfmrow** [EnlighterJS/EnlighterJS#75]
May you add a [Golang](https://golang.org/doc/) support, please ?

Thanks in advance.

**Comment by AndiDittrich** [comment]
golang has already been added...

**Comment by hfmrow** [comment]
Hi, 
I'm using Enlighter version 3.10.0 on WPress version 5.2.2
But can't find Golang in language menu.

**Comment by AndiDittrich** [comment]
golang ist available in EnlighterJS v3 - you're using the current release which only include the old livrary v2 - see https://github.com/EnlighterJS/Plugin.WordPress/issues/171

**Comment by hfmrow** [comment]
Ok, done.
I did not know there were add-ons for this plug-in .
Many thanks for explanations.

**Comment by AndiDittrich** [comment]
it's not an addon and should never be used as one ... it is just for testing.

**Comment by hfmrow** [comment]
Ok, and it will be included in main release one of theses days ?

**Comment by AndiDittrich** [comment]
not days...

**Comment by AndiDittrich** [comment]
i've just release the first beta version of Enlighter v4

https://github.com/EnlighterJS/Plugin.WordPress/releases/tag/v4.0.0-BETA1

**Comment by hfmrow** [comment]
Thank, i will try this as soon.
