### ISSUE TITLE
C#: verbatim string literal

### ISSUE THREAD

**Issue by Suplanus** [EnlighterJS/EnlighterJS#76]
I am using the [Beta 1 of Wordpress Plugin](https://github.com/EnlighterJS/Plugin.WordPress/issues/178).
But I think thats a problem of EnlighterJS it self:

This code is rendering wrong:

```csharp
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Forms;
using Eplan.EplApi.ApplicationFramework;
using Eplan.EplApi.Scripting;
public class Script
{
  [Start]
  public void Action()
  {
    InsertMacro(@"C:\Test\Test.ema", "/2");
  }
  private void InsertMacro(string macroFileName, string pageName)
  {
    Edit(pageName);
    Parallel.Invoke(() =>
                      InsertMacro(macroFileName),
                    KeyPress);
  }
}
```

![image](https://user-images.githubusercontent.com/2002916/61928266-31537480-af78-11e9-863d-5d5a4a3b42cb.png)

Example you can find [here](https://suplanus.de/fenstermakro-an-bestimmter-position-einfuegen/).

**Comment by AndiDittrich** [comment]
thanks for your report, the issue is causes by an invalid annotation rule

```
// annotations
{
    regex: /@[\W\w_][\w]+/gm,
    type: 's9'
}
```

**Comment by AndiDittrich** [comment]
the fixed version is available within the [master branch](https://github.com/EnlighterJS/EnlighterJS/tree/master/dist)

just update the files in `enlighter/resources/enlighterjs`

**Comment by Suplanus** [comment]
Big thanks for your work and the quick fix.
I replaced the files on the FTP and cleared the cache.

The problem is still [there](https://suplanus.de/fenstermakro-an-bestimmter-position-einfuegen/).

**Comment by AndiDittrich** [comment]
maybe you should use `csharp` as language and **NOT** `c` ...

**Comment by Suplanus** [comment]
Sorry 🤦‍♂ 
This post was converted from [Crayon](https://github.com/EnlighterJS/Plugin.WordPress/issues/136).

Thanks 😘
