### ISSUE TITLE
Single line code can be scrolled

### ISSUE THREAD

**Issue by E011011101001** [EnlighterJS/EnlighterJS#78]
When the code is only one line, you can scroll it up till the line disappears. (On the published page.)

Like that.
![Issue](https://user-images.githubusercontent.com/50290471/64085976-3c17db00-cd68-11e9-912c-9d6fb9efd57a.png)

**Comment by AndiDittrich** [comment]
HI @E011011101001 

the toolbar is larger than the content, therefore it will be hidden. scrollbars are normally not added by enlighterjs

------

* **quick solution** - disable the toolbar
* **full solution**     - not available
