### ISSUE TITLE
Python - colorcoding issue with % and /

### ISSUE THREAD

**Issue by johanhallgrenalingsas** [EnlighterJS/EnlighterJS#82]
Hi.

The signs '%' and '/' mixes up the colorcoding in python. Se img for examples.

![img 2019-11-05 08 50 48](https://user-images.githubusercontent.com/45819214/68200823-e8707a80-ffc0-11e9-8513-d6b420d606a4.png)
![img 2019-11-05 08 51 15](https://user-images.githubusercontent.com/45819214/68200825-e9091100-ffc0-11e9-9625-69baa2173746.png)

**Comment by AndiDittrich** [comment]
v2 or v3 ?

**Comment by johanhallgrenalingsas** [comment]
This issue appears on version 2.12. I tried 3.0.0 and that one doesn't have the same problem. So I will switch to 3.0.0 instead.

**Comment by AndiDittrich** [comment]
ok great :) v2 won't be fixed
