### ISSUE TITLE
Feature request: collapse long code

### ISSUE THREAD

**Issue by swissbyte** [EnlighterJS/EnlighterJS#87]
hi

It would be nice if the code block would automatically gray out after a globally defined amount of lines. This would be helpful if you want to post whole files insteaf of only snippets. 

Instead of graying out the block could also become scrollable... maybe a scrollable div?

Thanks!

**Comment by AndiDittrich** [comment]
Hi @swissbyte 

this feature request is related to EnlighterJS - generally it's possible to add a generic collapse handler based on a total given height in `px` - using linenumbers is difficult.

the dom structure already includes the required containers (same as used for horizontal scrolling)

**Comment by swissbyte** [comment]
Hi @AndiDittrich thanks for your fast reply. 

Size in pixel would be absolutley good enough :)

Thank you for your support!

**Comment by AndiDittrich** [comment]
i've added the collapse option/css but the control elements are missing - it requires a larger refactoring of the toolbars

![image](https://user-images.githubusercontent.com/1474107/71625533-a9d5f580-2be8-11ea-92b6-4f75f5269152.png)

**Comment by swissbyte** [comment]
wow
that was fast. 

Looks good!

**Comment by dbarj** [comment]
Hi @AndiDittrich . Do you mind giving any simple example how to enable this feature for WP even if the UI still does not support it? I noted there is no HTML data attributes for this yet. Thanks!

**Comment by AndiDittrich** [comment]
the css class `enlighter-collapse` https://github.com/EnlighterJS/EnlighterJS/blob/master/src/themes/core/base.less#L305 needs to be added to the generated EnlighterJS codeblock, you can try to add this class to the pre tag manually and enable the "copy css class" option within the advanced settings.

Or copy the css to your theme to override all EnlighterJS codeblocks

**Comment by dbarj** [comment]
Thanks for your help @AndiDittrich , this worked!

One last thing: what if I want to dynamically set the max-height for that given pre tag? Do you have any suggestion for this? I tried to force it using style but it's not working:

`<pre class="EnlighterJSRAW enlighter-collapse" style="max-height: 100px;" data-enlighter-language="generic">`

**Comment by AndiDittrich** [comment]
you have to use css classes, styles are not copied
