### ISSUE TITLE
Powershell highlighting enhancements

### ISSUE THREAD

**Issue by krysiekBP** [EnlighterJS/EnlighterJS#88]
Hi. I love Your plugin, it's great.
I found out, that there is no plugin for wordpress that higlights powershell correctly.
Can You add support for Powershell ?

Thanks!
Bartosz Pawlak

**Comment by AndiDittrich** [comment]
powershell support has been added to EnlighterJS some month ago.
A beta version of the Enlighter WordPress plugin (v4-beta1) - which includes EnlighterJS v3 - is available on GitHub

**Comment by krysiekBP** [comment]
WOW! Thats fantastic. Thanks!!

**Comment by krysiekBP** [comment]
I don't see any diffrence in highliting between shellscript and powrshell. Am i doing something wrong ?

**Comment by AndiDittrich** [comment]
maybe. but without additional information i'm unable to help your (url..)

**Comment by krysiekBP** [comment]
Webpage still in progress
http://pureit.com.pl/lets-start-with-powershell-part2/

**Comment by AndiDittrich** [comment]
everything looks fine in point of highlighting...but you're using it in a wrong way...

the highlighting is designed to highlight **powershell script** and **NOT** interactive console sessions including command output or especially the PS1 prompt sequence like `PS H:\>`

example: https://github.com/EnlighterJS/EnlighterJS/issues/23#issuecomment-231583793

**Comment by krysiekBP** [comment]
Got it.
I have added a full script in the same page. It looks much better.
Any plans for adding additional commandlets to be highlited? Not all of them are recognised by the plugin. Maybe I can edit if myself ?

**Comment by AndiDittrich** [comment]
the current highlighting rules such match nearly all common patterns. which one doesn't work ?
EnlighterJS is OpenSource - you can add any custom modification you want!

**Comment by krysiekBP** [comment]
FE $art=$line | select-string -Pattern select-string is not highlited. Get-ADuser is also not highlited.

ps. Thanks for support, You are great!

**Comment by krysiekBP** [comment]
I think I got it. in Regex You check for the first big letter in command!

**Comment by AndiDittrich** [comment]
i thought that uppercase character is the standard used in powershell ? (i'm not familiar with powershell -> bash user ;))

**Comment by krysiekBP** [comment]
windows is not case sensitive :) You can write whatever you like. Also there are a lot of aliases (select for select-object). I now where to change it and i will think of that if it will bother me 👍.
Again: Great plugin, Thanks!

**Comment by AndiDittrich** [comment]
ok, i've changed the regex to:

```js
/\b([A-Z]\w+(?:-\w+)+)\b/gi
```

**Comment by krysiekBP** [comment]
I know where to change it in the Js source code, but where to look for that in the plugin itself ?

**Comment by AndiDittrich** [comment]
you have to rebuild the library

**Comment by krysiekBP** [comment]
that will be hard.... ;) I have no compiling tools and almost zero knowledge :)
I will use A-Z for now in my webpage and wait for your new version :)

**Comment by AndiDittrich** [comment]
dirty workaround: search+replace within the minified js file ;)

**Comment by krysiekBP** [comment]
IS there something more that needs to be done ?
Some caching ?
I did change that (and added additinal commands (aliases like dir, ft, ftl, where and stuff like that) but no change :(

**Comment by AndiDittrich** [comment]
clear your browser cache and press "save settings" within the Enlighter settings page

**Comment by krysiekBP** [comment]
Can You also add the parameters of the commandlets to the highliting?
This should be "-command" format.
I have tried to create my own theme for coloring. Shoud I take *.less file from EnlighterJS-3.0.0\src\themes\ and put it to \activewordpresstheme\enlighter\file.less here ?
I think I need to figure it out, how to compile those files... ;)

**Comment by AndiDittrich** [comment]
there are two possible ways to create/derive themes:

1. use the minified single-theme versions in `dist/*.min.css`
    * rename the file (lowercase, only alphanum chars) as well as all occurrences in the file
    * apply custom modifications
    * upload the theme to your WordPress site `wp-content/themes/<yourtheme>/enlighter/mytheme.min.css
    * enable external theme support in `Enlighter -> Options - > Resources -> External Themes` 

2. copy + rename the theme source file in `src/themes/<name>.less` and rebuild theme via the gulp script 
     * using full custom themes assumes that you didn't use the default ones. you have to enqueue the css file on your own (adding them to your wordpress theme) and disable EnlighterJS default themes in `Enlighter -> Options - > Resources -> EnlighterJS themes` 


-----

regarding the parameters within highlighting: do you have any examples or official references ? does it match any of the [symbols](https://github.com/EnlighterJS/docs/blob/master/HighlightingEngine_and_Symbols.md) (exact match) ?

**Comment by krysiekBP** [comment]
Thanks.

Please check this sample from MS docs.
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/get-command?view=powershell-6

Its build like this "get-command -function value"
"-function" is a Word (i dont know any alfanumerical) so it should be
doable Wit regex (magic for me).
Also your regex Marks xxxx-zzzz-dddd-sssss also as command.
Cheers!

Bartosz

pt., 10 sty 2020, 12:28 użytkownik Andi Dittrich <notifications@github.com>
napisał:

**Comment by krysiekBP** [comment]
After putting the x.min.css file to /themes/enlighter I choose external Themes, but the theme doesn't appear in the theme list (i also did disable Enlighter themes). Enlighting is still done in the selected theme (or no highliting is done if the main ones are disabled).

**Comment by AndiDittrich** [comment]
the path for custom themes is 

`wp-content/themes/<yourtheme>/enlighter/mytheme.min.css`

**Comment by krysiekBP** [comment]
Now I can see this in the selection list! Greeat! :)

**Comment by AndiDittrich** [comment]
remove the `.min` from the filename:

theme name: `powershell` -> filename `powershell.css` - i have to state this in the docs

btw. NEVER use theme names used by the enlighter plugin for your custom themes

**Comment by krysiekBP** [comment]
When I take dracula or atomic css and change the background color - they stay the same (default ones). When I change the droid them, changing the background color works like a charm. Where is the difference ?

**Comment by AndiDittrich** [comment]
it causes an unexpected behaviour. rename the theme and everything is fine OR disable all EnlighterJS css resources and enqueue the EnlighterJS theme (including the second line) manually

**Comment by krysiekBP** [comment]
You misunderstood me.
I take css from dracula/atomic.
I change the name of the file and change the entries inside to point to new name (fe powershell, test etc.). I also delete the second line from the file
Then I put it into the themes\mytheme\enlighter folder
I change the background color in the css file - it does not take effect.
I do the same for the "droid" theme (change the name, change in the file.. .etc) and it works.
Looks like there are some settings in the atomic/dracula theme that blocks it :(

**Comment by AndiDittrich** [comment]
oh ok sry. did you checked the css classes with chrome/firefox developer tools (inspect element) ? maybe the css enqueue order is wrong or some styles get overridden

**Comment by krysiekBP** [comment]
I still have some problems with themes.
I have disabled the original themes, and my file (taken from the original one) is behaving strange
http://pureit.com.pl/lets-start-with-powershell-part2/4/.
Then I enable original themes (only enable, still have my theme selected), it looks more like the original one ( but the RAW/Copy ... buttons looks strange :( )

**Comment by AndiDittrich** [comment]
currently the base styles (second line of the `theme.min.css` file) is missing - this is required in case you've disabled the default css

**Comment by krysiekBP** [comment]
Finally! I got what I wanted!
Thanks a lot.
When I enable default themes, my theme is broken. 
Since I will need only one theme, then I can work with the customized one.
Now it works as suspected.
brilliant!
Cheers!
