### ISSUE TITLE
Custom languages

### ISSUE THREAD

**Issue by ajtruckle** [EnlighterJS/EnlighterJS#90]
I don't know if this is possible or not. Here is some sample code using "generic":

![Sample-BBPress](https://user-images.githubusercontent.com/7985331/74569879-5c80ce00-4f73-11ea-8a41-2a0b8f245d94.png)

The above is a custom language used by my software. It looks like this in my software:

![Sample-PTS](https://user-images.githubusercontent.com/7985331/74569916-70c4cb00-4f73-11ea-9cea-5e7e7911de88.png)

is there any way to establish our own "language"? I have a few keywords as documented in my online help [here](https://help-pts.publictalksoftware.co.uk/pts-script-command-syntax.html). Is it possible to create a bespoke language for syntax highlighting?

**Comment by ajtruckle** [comment]
I have had a look at the documentation for this EnlighterJS v3 and it doesn't look like it is a plugin and thus not exposed with any GUI for setting configuration.

I appreciate you have documentation but I don't quite understand how to use it. At the moment I am sticking with the plugin you have provided.

**Comment by AndiDittrich** [comment]
EnlighterJS is the core highlighting library - the Enlighter Wordpress plugins integrates it into WordPress including the editing plugins.

without knowledge in advanced javascript (es6, regex) it is impossible to add new languages, sry!

**Comment by ajtruckle** [comment]
Understood. Either way, even if I can't add a bespoke language for highlighting, it is not fully clear to me how to install and use it compared to the v2 plugin.

**Comment by AndiDittrich** [comment]
you can just use Enlighter v4-beta1.

**Comment by ajtruckle** [comment]
Link to release page?

**Comment by AndiDittrich** [comment]
look into the repository....
