### ISSUE TITLE
How to enlight HTML?

### ISSUE THREAD

**Issue by LuizGMX** [EnlighterJS/EnlighterJS#94]
I'm trying to enlight the data from a HTML file, but the website keeps trying to render the content of it.

**Comment by AndiDittrich** [comment]
```html
<pre data-enlighter-language="html">
your ESCAPED html content
</pre>
```

**Comment by LuizGMX** [comment]
Oh thanks it worked, do you know a way to get a html and scape it? A function, i mean.

**Comment by AndiDittrich** [comment]
this depends on your programming language/framework

**Comment by LuizGMX** [comment]
javascript

**Comment by AndiDittrich** [comment]
https://www.google.com/search?q=javascript+escape+html

**Comment by LuizGMX** [comment]
I got, it with jquery and javascript, thank you.
