### ISSUE TITLE
new version 4 - bug in SQL (comments are not properly interpreted)

### ISSUE THREAD

**Issue by petr-hybler** [EnlighterJS/EnlighterJS#97]
Hello, when you use a quote in a single-line comment it is NOT interpreted as any other character but as a start of STRING

-- call the package's procedure
therefore the rest of the code highlight is "destroyed"

**Comment by AndiDittrich** [comment]
the `--` style comments are currently ignored (invalid regex/wrong order). i will fix this today - sry!

**Comment by AndiDittrich** [comment]
fixed in the dev branch

![image](https://user-images.githubusercontent.com/1474107/79436731-8a18e080-7fd1-11ea-82c9-e0260298a340.png)

**Comment by AndiDittrich** [comment]
Enlighter v4.1 has been released including EnlighterJS v3.2.0
